0001 001e 037710  OPENPORT    007458                                   C/ASM  SPOOLJCR.EXE
0001 0044 037710  CLOSEPORT   0074cc                                   C/ASM  SPOOLJCR.EXE
0001 003d 037710  MANDAPAQ    0074e8                                   C/ASM  SPOOLJCR.EXE
0001 003e 037710  RESPUESTA   007536                                   C/ASM  SPOOLJCR.EXE
0001 0020 037710  INITFISCAL  007556                                   C/ASM  SPOOLJCR.EXE
0001 001f 037710  SETBAUD     00776a                                   C/ASM  SPOOLJCR.EXE
0001 0030 037710  FILE        00aa80                                   C/ASM  SPOOLJCR.EXE
0001 007b 037710  ERRORLEVEL  00b30e                                   C/ASM  SPOOLJCR.EXE
0001 007c 037710  __QUIT      00b33c                                   C/ASM  SPOOLJCR.EXE
0001 008b 037710  __QQPUB     0116e2                                   C/ASM  SPOOLJCR.EXE
0001 0079 037710  PROCNAME    0140da                                   C/ASM  SPOOLJCR.EXE
0001 007a 037710  PROCLINE    014112                                   C/ASM  SPOOLJCR.EXE
0001 0002 037710  SET         0142d2                                   C/ASM  SPOOLJCR.EXE
0001 008f 037710  __MXRELEAS  01629a                                   C/ASM  SPOOLJCR.EXE
0001 0071 037710  ERRORBLOCK  0175e0                                   C/ASM  SPOOLJCR.EXE
0001 000f 037710  NETERR      017674                                   C/ASM  SPOOLJCR.EXE
0001 0042 037710  ALERT       02023c                                   C/ASM  SPOOLJCR.EXE
0001 0078 037710  OUTERR      020692                                   C/ASM  SPOOLJCR.EXE
0001 004c 037710  DISPBOX     022128                                   C/ASM  SPOOLJCR.EXE
0001 0025 037710  MAXROW      022440                                   C/ASM  SPOOLJCR.EXE
0001 0026 037710  MAXCOL      022450                                   C/ASM  SPOOLJCR.EXE
0001 0048 037710  SETCOLOR    022a38                                   C/ASM  SPOOLJCR.EXE
0001 008d 037710  COLORSELEC  022b58                                   C/ASM  SPOOLJCR.EXE
0001 008c 037710  SETCURSOR   022b7c                                   C/ASM  SPOOLJCR.EXE
0001 0024 037710  SAVESCREEN  022b96                                   C/ASM  SPOOLJCR.EXE
0001 002a 037710  RESTSCREEN  022d98                                   C/ASM  SPOOLJCR.EXE
0001 0016 037710  SCROLL      022f72                                   C/ASM  SPOOLJCR.EXE
0001 00d8 037710  RDDREGISTE  0247d0                                   C/ASM  SPOOLJCR.EXE
0001 00d0 037710  RDDSETDEFA  024a70                                   C/ASM  SPOOLJCR.EXE
0001 0014 037710  DBCLOSEARE  024b76                                   C/ASM  SPOOLJCR.EXE
0001 000b 037710  DBUSEAREA   024bb2                                   C/ASM  SPOOLJCR.EXE
0001 0031 037710  FOPEN       02737e                                   C/ASM  SPOOLJCR.EXE
0001 0040 037710  FCLOSE      0273ee                                   C/ASM  SPOOLJCR.EXE
0001 0034 037710  FREADSTR    027526                                   C/ASM  SPOOLJCR.EXE
0001 0041 037710  FERASE      0276fc                                   C/ASM  SPOOLJCR.EXE
0001 0033 037710  FERROR      02779a                                   C/ASM  SPOOLJCR.EXE
0001 00c7 037710  NATIONMSG   027fd2                                   C/ASM  SPOOLJCR.EXE
0001 00c8 037710  NEXTKEY     028488                                   C/ASM  SPOOLJCR.EXE
0001 0043 037710  LASTKEY     0284f8                                   C/ASM  SPOOLJCR.EXE
0001 0084 037710  SETKEY      0286f0                                   C/ASM  SPOOLJCR.EXE
0001 00b2 037710  QQOUT       028cba                                   C/ASM  SPOOLJCR.EXE
0001 0089 037710  DISPOUT     028e5a                                   C/ASM  SPOOLJCR.EXE
0001 004d 037710  DEVOUT      028fb6                                   C/ASM  SPOOLJCR.EXE
0001 0085 037710  __XHELP     029460                                   C/ASM  SPOOLJCR.EXE
0001 003a 037710  ALLTRIM     0296ea                                   C/ASM  SPOOLJCR.EXE
0001 0038 037710  MEMOLINE    0297c8                                   C/ASM  SPOOLJCR.EXE
0001 0036 037710  MLCOUNT     029a78                                   C/ASM  SPOOLJCR.EXE
0001 008e 037710  ASCAN       029ef2                                   C/ASM  SPOOLJCR.EXE
0001 00d6 037710  _VDBFNTX    03f9d6                                   C/ASM  SPOOLJCR.EXE
0001 00da 037710  _VDBF       03ffd0                                   C/ASM  SPOOLJCR.EXE
0001 0001 037710  SPOOLJCR    042000   DYN                                    SPOOLJCR.EXE
0001 0021 037710  CANCELTICK  042795   DYN                                    SPOOLJCR.EXE
0001 006e 037710  CLIPINIT$   0427e1   DYN   INIT PROC                        SPOOLJCR.EXE
0001 0070 037710  SYSINIT     0427f7   DYN                                    SPOOLJCR.EXE
0001 00d4 037710  _NTXERR     0427fb   DYN                                    SPOOLJCR.EXE
0001 0022 037710  CLOSEFISCA  042800   DYN                                    SPOOLJCR.EXE
0001 0023 037710  CLOSENOFIS  042825   DYN                                    SPOOLJCR.EXE
0001 0019 037710  MENSAJE7    04284a   DYN                                    SPOOLJCR.EXE
0001 005d 037710  HEXATOINT   04290c   DYN                                    SPOOLJCR.EXE
0001 0090 037710  READMODAL   042a10   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 0098 037710  GETPREVALI  042afc   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00a0 037710  GETDOSETKE  042b8a   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 0017 037710  __KILLREAD  042bf3   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 003c 037710  ENVIAR      042c00   DYN                                    SPOOLJCR.EXE
0001 006f 037710  ERRORSYS    042f93   DYN                                    SPOOLJCR.EXE
0001 0086 037710  READVAR     042fad   DYN            STATICS$ ref: 87        SPOOLJCR.EXE
0001 0087 037710  STATICS$    042fd3   DYN   STAT INIT                        SPOOLJCR.EXE
0001 0088 037710  STATICS$    042fdf   DYN   STAT INIT                        SPOOLJCR.EXE
0001 00c5 037710  UPDATED     042fed   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00d7 037710  DBFONLY     042ff8   DYN                                    SPOOLJCR.EXE
0001 0053 037710  GETERRORS   043000   DYN                                    SPOOLJCR.EXE
0001 0063 037710  OKCANCEL    0434b4   DYN                                    SPOOLJCR.EXE
0001 0076 037710  ERRORMESSA  0436c5   DYN   STATIC                           SPOOLJCR.EXE
0001 0083 037710  __SETHELPK  0437d7   DYN                                    SPOOLJCR.EXE
0001 00d1 037710  RDDSYS      0437fc   DYN                                    SPOOLJCR.EXE
0001 0072 037710  DEFERROR    043800   DYN   STATIC                           SPOOLJCR.EXE
0001 0003 037710  __SETCENTU  043a43   DYN                                    SPOOLJCR.EXE
0001 006c 037710  __ATPROMPT  043afb   DYN            STATICS$ ref: 88        SPOOLJCR.EXE
0001 0096 037710  GETREADER   043b2c   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00c4 037710  __SETFORMA  043bb6   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00c0 037710  GETACTIVE   043bd6   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 006d 037710  __MENUTO    043c00   DYN            STATICS$ ref: 88        SPOOLJCR.EXE
0001 00bf 037710  READEXIT    043fb1   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00c6 037710  READINSERT  043fc8   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00cb 037710  READKILL    043fdf   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 009d 037710  GETAPPLYKE  044000   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 009e 037710  GETPOSTVAL  0442d6   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 0094 037710  POSTACTIVE  0443d2   DYN   STATIC   STATICS$ ref: 91        SPOOLJCR.EXE
0001 00cf 037710  DBFNTX      0443fa   DYN                                    SPOOLJCR.EXE
0001 0093 037710  SETTLE      044400   DYN   STATIC   STATICS$ ref: 91        SPOOLJCR.EXE
0001 0092 037710  CLEARGETSY  044555   DYN   STATIC   STATICS$ ref: 91        SPOOLJCR.EXE
0001 0097 037710  RESTOREGET  0445e5   DYN   STATIC   STATICS$ ref: 91        SPOOLJCR.EXE
0001 00c1 037710  GETREADVAR  044646   DYN   STATIC   STATICS$ ref: 91        SPOOLJCR.EXE
0001 00a2 037710  SHOWSCOREB  0446b3   DYN   STATIC   STATICS$ ref: 91        SPOOLJCR.EXE
0001 00b6 037710  DATEMSG     044706   DYN   STATIC   STATICS$ ref: 91        SPOOLJCR.EXE
0001 00cc 037710  READUPDATE  04476f   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00cd 037710  READFORMAT  04478f   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 0091 037710  STATICS$    0447af   DYN   STAT INIT                        SPOOLJCR.EXE
0001 00ce 037710  RDDINIT$    0447bd   DYN   INIT PROC                        SPOOLJCR.EXE
0001 00d2 037710  INITHANDL$  0447d0   DYN   INIT PROC                        SPOOLJCR.EXE
0001 00c9 037710  RANGECHECK  044800   DYN            STATICS$ ref: 91        SPOOLJCR.EXE
0001 00d3 037710  LOCKERRHAN  0448ee   DYN   STATIC                           SPOOLJCR.EXE
0001 00d5 037710  DBFNTXINI$  044917   DYN   INIT PROC                        SPOOLJCR.EXE
0001 00d9 037710  DBFINIT$    04492b   DYN   INIT PROC                        SPOOLJCR.EXE
