#include "colores.ch"
SET COLOR TO COLOR0
@8,47 TO 11,63
@9,48, 10,62 BOX 'ллллллллл'

PUBLIC OPCION

SET COLOR TO SELECT1
@9,48 SAY ' HACER ARQUEO  '
@9,48 PROMPT ' HACER ARQUEO  '

SET COLOR TO N/W
@10,48 SAY ' LISTAR ARQUEO '
SET COLOR TO W/B
@10,48 PROMPT ' LISTAR ARQUEO '

MENU TO OPCION
DO CASE
   CASE OPCION=1
      SET COLOR TO COLOR8
      @9,48 SAY ' HACER ARQUEO  '
      SET COLOR TO N/W+
      DO ARQCAJA
      RETURN
   CASE OPCION=2
      SET COLOR TO N/W+
      @10,48 SAY ' LISTAR ARQUEO '
      SET COLOR TO LETRASC0
   OTHERWISE
      RETURN
ENDCASE
USE ARQUEOS
INDEX ON FECHA TO ORDFEC
GO TOP
SET COLOR TO COLOR0
*SET COLOR TO COLOR4
@8,1 TO 23,78
@9,2 CLEAR TO 22,76
@21,2 TO 21,77
@19,2 TO 19,77
@20,2 CLEAR TO 20,77
@22,2 CLEAR TO 22,77
@22,8 SAY '<ENTER> Imprimir el arqueo     <F5> Imprime todos     <ESC> Salir'
SET COLOR TO COLOR10
@20,30 SAY 'Arqueos de Cajas'
@22,9 SAY 'ENTER'
@22,40 SAY 'F5'
@22,63 SAY 'ESC'
DECLARE CAMP[6]
CAMP[1]='FECHA'
CAMP[2]='TOTVENTAS'
CAMP[3]='TOTGASTOS'
CAMP[4]='DEBERIA'
CAMP[5]='ENCAJA'
CAMP[6]='ENCAJA-DEBERIA'
DECLARE CABEZ[6]
CABEZ[1]=' Fechas'
CABEZ[2]='Total Ventas'
CABEZ[3]='Total Gastos'
CABEZ[4]='DeberЁa Haber'
CABEZ[5]='Dinero Existente'
CABEZ[6]='Diferencia'
DECLARE SEPAR[6]
SEPAR[1]='Ф'
SEPAR[2]='Ф'
SEPAR[3]='Ф'
SEPAR[4]='Ф'
SEPAR[5]='Ф'
SEPAR[6]='Ф'
SET CURSOR OFF
CLEAR TYPEAHEAD
SET COLOR TO COLOR6
@24,1 SAY 'Buscar:                                                                       '
SET COLOR TO COLOR7
DBEDIT(9,2,18,77,CAMP,'MOD3','',CABEZ,SEPAR)
IF LASTKEY()=27
   CLOSE
   FERASE('.\ESC\TEMPO.DBF')
   RETURN
ENDIF
IF LASTKEY()=13
   STORE 0 TO TODOS
ENDIF
IF LASTKEY()=-4
   STORE 1 TO TODOS
ENDIF
DO PRNARQ
CLOSE
FERASE('.\ESC\TEMPO.DBF')
RETURN
