#include "colores.ch"
SET CENTURY ON
SET DATE TO FRENCH

USE .\ESC\BACKUP
STORE FECHA TO VFECHA
STORE BACKUPNRO TO VAR1
STORE DATE() TO VECHA_ACT




IF VAR1<10
   STORE '.\ESC\BACKUP\' TO RUTA1
   STORE STR(0,1,0) TO V0
   STORE STR(VAR1,1,0) TO VNUM
   STORE RUTA1+V0+VNUM TO RUTA
   STORE V0+VNUM TO RUTA3
   STORE RUTA+'\' TO RUTA2
ELSE
   STORE '.\ESC\BACKUP\' TO RUTA1
   STORE STR(VAR1,2,0) TO VNUM
   STORE VNUM TO RUTA3
   STORE RUTA1+VNUM TO RUTA
   STORE RUTA+'\' TO RUTA2
ENDIF


IF VFECHA<VECHA_ACT
  HACE_BACK()
ENDIF





FUNCTION HACE_BACK
IF VAR1<16
STORE VAR1+1 TO VAR1
  RUN DELTREE /Y &RUTA\*.*
  run COPY .\esc\*.dbf .\ESC\BACKUP\&RUTA3
  USE .\esc\BACKUP
  ZAP
  APPEND BLANK
  REPLACE BACKUPNRO WITH VAR1
  REPLACE FECHA WITH VECHA_ACT
ENDIF

IF VAR1=16
  STORE 1 TO VAR1
  USE .\esc\BACKUP
  ZAP
  APPEND BLANK
  REPLACE BACKUPNRO WITH VAR1
  REPLACE FECHA WITH VECHA_ACT
ENDIF
RETURN NIL

RETURN
