#include "colores.ch"
USE MERCA
INDEX ON DETALLE TO ORDDET
GO TOP
SAVE SCREEN TO JERI
DO WHILE .T.
   SET COLOR TO COLOR4
   @8,1 TO 23,78
   @9,2 CLEAR TO 22,76
   @21,2 TO 21,77
   @19,2 TO 19,77
   @20,2 CLEAR TO 20,77
   @22,2 CLEAR TO 22,77
   @22,11 SAY '        Tomar'
   @22,58 SAY '      Salir'
   @20,48 SAY 'Por C¢digo -      Por Detalle'
   SET COLOR TO COLOR10
   @20,5 SAY 'Art¡culos ordenados:'
   @20,43 SAY '<F2>'
   @20,61 SAY '<F3>'
   @22,11 SAY '<ENTER>'
   @22,58 SAY '<ESC>'

   DECLARE CAMP[2]
   CAMP[1]='CODIGO'
   CAMP[2]='DETALLE'
   DECLARE CABEZ[2]
   CABEZ[1]=' C¢digo'
   CABEZ[2]='                       Detalle'
   DECLARE SEPAR[2]
   SEPAR[1]='Ä'
   SEPAR[2]='Ä'
   SET CURSOR OFF
   CLEAR TYPEAHEAD
   SET COLOR TO COLOR6
   @24,1 SAY 'Buscar:                                                                       '
   SET COLOR TO COLOR7
   DBEDIT(9,2,18,77,CAMP,'FUNMOD','',CABEZ,SEPAR)
   IF LASTKEY()=-1
      INDEX ON CODIGO TO ORDCOD
      GO TOP
      LOOP
   ENDIF
   IF LASTKEY()=-2
      INDEX ON DETALLE TO ORDDET
      GO TOP
      LOOP
   ENDIF
   IF LASTKEY()=27
      RETURN
   ENDIF
   STORE CODIGO TO VCODIGO
   STORE DETALLE TO VDETALLE
   STORE CODIGBARRA TO VBARRA
   STORE PCOSTO TO VPCOSTO
   STORE GANANCIA TO VGANANCIA
   STORE RECNO() TO REGISTRO
   EXIT
ENDDO
CLEAR
DO WHILE .T.
   @0,0 TO 2,30
   SET COLOR TO COLOR3
   @1,2 SAY 'ESTACION DE SERVICIO CENTRO'
   numero=LEFT(DTOC(DATE()),2)
   DIA=TDIAS(cdow(DATE()))
   MES=TMES(CMONTH(DATE()))
   ANIO=ALLTRIM(STR(YEAR(DATE())))
   VFECHA=DIA+' '+numero+' de '+MES+' de '+ANIO
   LL=79-LEN(VFECHA)
   SET COLOR TO COLOR0
   @1,LL-7 SAY 'Fecha: '
   @3,20 TO 5,59
   SET COLOR TO COLOR3
   @4,23 SAY 'PANTALLA DE CONSULTA DE MERCADERIA'
   @1,LL SAY VFECHA
   SET CURSOR ON
   SET COLOR TO COLOR0
   @6,0 SAY REPLICATE('Ä',79)
   @7,1 SAY 'C¢digo : '
   SET COLOR TO COLOR6
   @7,10 SAY VCODIGO
   @9,10 SAY VDETALLE PICTURE '@!'
   @11,19 SAY VBARRA PICTURE '99999999999999'
   @13,19 SAY VPCOSTO PICTURE '9999.999'
   @15,17 SAY VGANANCIA PICTURE '999.99'
   SET COLOR TO COLOR0
   @8,0 SAY REPLICATE('Ä',79)
   @9,1 SAY 'Detalle:'
   @10,0 SAY REPLICATE('Ä',79)
   @11,1 SAY 'C¢digo de Barra:'
   @12,0 SAY REPLICATE('Ä',79)
   @13,1 SAY 'Precio de Costo:'
   @14,0 SAY REPLICATE('Ä',79)
   @15,1 SAY '% de ganancia:'
   @16,0 SAY REPLICATE('Ä',79)
   VSINIVA=VPCOSTO*VGANANCIA/100+VPCOSTO
   VCONIVA=VSINIVA*21/100+VSINIVA
   @17,1 SAY 'Precio sin IVA:'
   SET COLOR TO COLOR3
   @17,17 SAY '$ '+ALLTRIM(STR(VSINIVA))
   SET COLOR TO COLOR0
   @18,0 SAY REPLICATE('Ä',79)
   @19,1 SAY 'Precio con IVA:'
   SET COLOR TO COLOR3
   @19,17 SAY '$ '+ALLTRIM(STR(VCONIVA))
   SET COLOR TO COLOR0 
   @20,0 SAY REPLICATE('Ä',79)
   SET CURSOR OFF
   SET COLOR TO COLOR3
   @23,26 SAY 'Pulse una tecla para Salir'
   SET COLOR TO COLOR0
   INKEY(0)
   RETURN
ENDDO
