#include "colores.ch"
***  RUTINA DE COPIA DE SEGURIDAD ***

INKEY(1)
IF !FILE('.\ESC\PKZIP.EXE')
   SET COLOR TO COLOR0
   @12,12 TO 14,66
   @13,13 CLEAR TO 13,65
   TONE(500,2)
   @13,16 SAY 'El Archivo para compresi¢n           no existe'
   SET COLOR TO COLOR8
   @13,43 SAY 'PKZIP.EXE'
   SET COLOR TO COLOR0
   INKEY(8)
   RETURN
ENDIF
SET COLOR TO COLOR0
CLEAR
SET CURSOR OFF
@3,10 TO 21,69 DOUBLE 
@6,11 to 6,68
@17,11 to 17,68
@4,11 CLEAR to 5,68
@18,11 CLEAR to 20,68
SET COLOR TO COLOR10
@4,31 SAY 'COPIA DE SEGURIDAD' 
@5,20 SAY '*** PARA ESTACION DE SERVICIO CENTRO ***'
DO WHILE .T.
  SAVE SCREEN TO PANPAN
  SET COLOR TO COLOR0
  @7,11 CLEAR TO 16,68
  @10,11 to 10,68
  @7,22 SAY 'Se har n copia de las BASES de DATOS'
  SET COLOR TO COLOR8
  @7,44 SAY 'BASES'
  @7,53 SAY 'DATOS'
  @11,19 CLEAR to 16,60
  SET COLOR TO COLOR0
  @19,17 say 'Confirme con <ENTER>       o cancele con <ESC>'
  SET COLOR TO COLOR10
  @19,30 say '<ENTER>'
  @19,58 say '<ESC>'
  SET COLOR TO COLOR0
  STORE 'A:\' TO DISCO
  @12,20 CLEAR TO 12,58
  @12,34 SAY 'Copiar en'
  CLOSE ALL
  DO WHILE .T.
     SET COLOR TO COLOR10
     @12,44 SAY LEFT(DISCO,2)
     SET COLOR TO COLOR0
     @18,11 CLEAR to 20,68
     @14,18 SAY 'Inserte un diskete para BASES en la unidad'
     @16,32 SAY 'y pulse'
     SET COLOR TO COLOR8
     @14,61 SAY LEFT(DISCO,2)
     @16,41 SAY '<ENTER>'
     SET COLOR TO COLOR9
     @18,11 SAY ' ­ ATENCION ! '
     SET COLOR TO COLOR3
     @18,26 SAY 'SI EL DISKETE QUE VA A USAR CONTIENE DATOS,'
     @20,26 SAY 'ESTOS SERAN ELIMINADOS PARA CREAR LA COPIA.'
     SET COLOR TO COLOR0
     INKEY(0)
     IF LASTKEY()=27
        RETURN
     ENDIF
     KKK=FCREATE('A:\BASES.RA0',0)
     MANI='123'
     FWRITE(KKK,MANI)
     FCLOSE(KKK)
     IF FERROR()<>0
        @18,11 CLEAR to 20,68
        SET COLOR TO COLOR8
        @19,33 SAY ' NO HAY DISCO '
        SET COLOR TO COLOR0
        INKEY(3)
        LOOP
     ENDIF
     IF FILE('A:\BASES.RA0')
        RUN DEL A:\BASES.RA0 >NUL
     ENDIF
     EXIT
  ENDDO
  RUTA='COPY .\ESC\BASES.ZIP A:\ >NUL'
  RUTA2='COPY .\ESC\INDICES.ZIP A:\ >NUL'
  SET COLOR TO COLOR0
  @18,11 CLEAR to 20,68
  @11,11 CLEAR to 16,68
  @12,33 SAY 'Copiando en'
  SET COLOR TO COLOR6
  @12,45 SAY LEFT(DISCO,2)
  SET COLOR TO COLOR0
  @19,23 SAY 'Copiando BASES de datos'
  SET COLOR TO COLOR8
  @19,47 SAY '­ ESPERE !'
  SET COLOR TO COLOR0
  IF FILE('A:\BASES.ZIP')
     RUN DEL A:\BASES.ZIP >NUL
  ENDIF
  RUN DELTREE /Y A:\*.* >NUL
  RUN PKZIP .\ESC\BASES .\ESC\*.DB* >NUL
  RUN &RUTA
  RUN DEL .\ESC\BASES.ZIP >NUL
  @7,18 SAY 'Se crearon las copias de las BASES de DATOS.'
  @8,38 SAY 'ahora'
  @9,18 SAY 'Se har  copia de los INDICES de ORDENAMIENTO'
  @11,11 CLEAR to 16,68
  SET COLOR TO COLOR8
  @9,39 SAY 'INDICES'
  @9,50 SAY 'ORDENAMIENTO'
  TONE(1200,1)
  TONE(1200,1)
  TONE(1200,1)
  DO WHILE .T.
     SET COLOR TO COLOR0
     @18,11 CLEAR to 20,68
     @14,17 SAY 'Inserte un diskete para INDICES en la unidad'
     @16,32 SAY 'y pulse'
     SET COLOR TO COLOR8
     @14,62 SAY LEFT(DISCO,2)
     SET COLOR TO COLOR10
     @16,41 SAY '<ENTER>'
     SET COLOR TO COLOR9
     @18,11 SAY ' ­ ATENCION ! '
     SET COLOR TO COLOR0
     @18,26 SAY 'SI EL DISKETE QUE VA A USAR CONTIENE DATOS,'
     @20,26 SAY 'ESTOS SERAN ELIMINADOS PARA CREAR LA COPIA.'
     INKEY(0)
     IF LASTKEY()=27
        RETURN
     ENDIF
     KKK=FCREATE('A:\BASES.RA0',0)
     MANI='123'
     FWRITE(KKK,MANI)
     FCLOSE(KKK)
     IF FERROR()<>0
        @18,11 CLEAR to 20,68
        SET COLOR TO COLOR8
        @19,33 SAY ' NO HAY DISCO '
        SET COLOR TO COLOR0
        INKEY(3)
        LOOP
     ENDIF
     IF FILE('A:\BASES.RA0')
        RUN DEL A:\BASES.RA0 >NUL
     ENDIF
     EXIT
  ENDDO
  SET COLOR TO COLOR0
  @18,11 CLEAR to 20,68
  @11,11 CLEAR to 16,68
  @12,33 SAY 'Copiando en'
  SET COLOR TO COLOR6
  @12,45 SAY LEFT(DISCO,2)
  SET COLOR TO COLOR0
  @19,18 SAY 'Copiando INDICES de ordenamiento '
  SET COLOR TO COLOR8
  @19,51 SAY '­ ESPERE !'
  SET COLOR TO COLOR0
  IF FILE('A:\INDICES.RAR')
     RUN DEL A:\INDICES.RAR >NUL
  ENDIF
  RUN DELTREE /Y A:\*.* >NUL
  RUN PKZIP .\ESC\INDICES .\ESC\*.NTX >NUL
  RUN &RUTA2
  RUN DEL .\ESC\INDICES.ZIP >NUL
  @8,38 SAY '     '
  @9,18 SAY 'Se crearon copias de INDICES de ORDENAMIENTO'
  @12,20 CLEAR TO 12,58
  @12,36 SAY 'en unidad'
  @18,11 CLEAR to 20,68
  @11,11 CLEAR to 16,68
  TONE(1200,1)
  TONE(1200,1)
  TONE(1200,1)
  SET COLOR TO COLOR8
  @18,29 SAY '...COPIA FINALIZADA...'
  SET COLOR TO COLOR0
  @20,33 SAY 'pulse'
  SET COLOR TO COLOR10
  @20,40 SAY '<ENTER>'
  SET COLOR TO COLOR0
  tone(1200,1)
  tone(1200,1)
  tone(1200,1)
  INKEY(0)
  USE PARAMETR
  GO TOP
  REPLACE FECHACOPIA WITH DATE()
  CLEAR
  RETURN
ENDDO
