#include "colores.ch"
***  RUTINA DE LECTURA DE BASES DE UN DISKETTE ***

SET COLOR TO COLOR0
CLEAR
SET CURSOR OFF
SET COLOR TO COLOR3
@3,10 TO 23,69 DOUBLE 
SET COLOR TO COLOR0
@6,11 to 6,68
@17,11 to 17,68
@4,11 CLEAR to 5,68
@18,11 CLEAR to 22,68
SET COLOR TO COLOR3
@4,30 SAY 'LEER DATOS ANTERIORES' 
@5,22 SAY '*** ESTACION DE SERVICIOS CENTRO ***'
SET COLOR TO COLOR0
SAVE SCREEN TO PANPAN
DO WHILE .T. 
   SET COLOR TO COLOR0
   @18,11 CLEAR to 22,68
   @19,18 SAY 'Inserte un diskete para LEER en la unidad'
   @21,32 SAY 'y pulse'
   SET COLOR TO COLOR9
   @19,60 SAY 'A:'
   SET COLOR TO COLOR6
   @21,41 SAY '<ENTER>'
   SET COLOR TO COLOR0
   INKEY(0)
   IF LASTKEY()=27
      RETURN
   ENDIF
   @18,11 CLEAR to 22,68
   SET COLOR TO COLOR9
   @20,35 SAY 'UN MOMENTO'
   SET COLOR TO COLOR0
   KKK=FCREATE('A:\BASES.RA0',0)
   MANI='123'
   FWRITE(KKK,MANI)
   FCLOSE(KKK)
   IF FERROR()<>0
      @18,11 CLEAR to 22,68
      SET COLOR TO COLOR13
      @20,33 SAY ' NO HAY DISCO '
      SET COLOR TO COLOR0
      INKEY(3)
      RESTORE SCREEN FROM PANPAN
      LOOP
   ENDIF
   IF FILE('A:\BASES.RA0')
      RUN DEL A:\BASES.RA0 >NUL
   ENDIF
   EXIT
ENDDO
SAVE SCREEN TO PANPAN
DO WHILE .T.
   SET DEFAULT TO .\CHURTI
   SET PATH TO .\CHURTI
   SET COLOR TO COLOR0
   @18,11 CLEAR to 22,68
   SET COLOR TO COLOR9
   @20,35 SAY 'UN MOMENTO'
   SET COLOR TO COLOR0
   PUBLIC TABLA1
   TABLA1=DIRECTORY('A:\*.ZIP')
   A1=LEN(TABLA1)
   IF A1=0
      TONE(500,2)
      SET COLOR TO COLOR0
      @13,21 TO 15,56
      @14,22 CLEAR TO 14,55
      SET COLOR TO COLOR9
      @14,23 SAY 'NO EXISTEN DATOS EN ESE DISKETTE'
      SET COLOR TO COLOR0
      INKEY(3)
      EXIT
   ENDIF
   SET COLOR TO COLOR0
   CLEAR
   @1,0 SAY ' ESPERE POR FAVOR...'
   @3,0 SAY ' TRASLADANDO LOS DATOS    '
   @4,0 SAY ' DESCOMPRIMIENDO DATOS    '
   @5,0 SAY ' CARGANDO DATOS A MEMORIA '
   INKEY(1)
   SET COLOR TO COLOR9
   @3,0 SAY ' TRASLADANDO LOS DATOS    '
   SET COLOR TO COLOR0
   RUN MD .\CHURTI >NUL
   RUN CD .\CHURTI >NUL
   RUN COPY A:\*.ZIP .\CHURTI >NUL
   @3,0 SAY ' TRASLADANDO LOS DATOS    '
   SET COLOR TO COLOR9
   @4,0 SAY ' DESCOMPRIMIENDO DATOS    '
   SET COLOR TO COLOR0
   RUN PKUNZIP .\CHURTI\*.ZIP >NUL
   RUN REN .\CHURTI\*.DBF VENTAS.DBF >NUL
   @4,0 SAY ' DESCOMPRIMIENDO DATOS    '
   SET COLOR TO COLOR9
   @5,0 SAY ' CARGANDO DATOS A MEMORIA '
   SET COLOR TO COLOR0
   USE VENTAS
   INDEX ON FECHA TO ORDFEC
   GO TOP
   CLEAR
   IF EOF()
      TONE(500,2)
      SET COLOR TO COLOR0
      @13,29 TO 15,48
      @14,30 CLEAR TO 14,47
      SET COLOR TO COLOR9
      @14,31 SAY 'NO EXISTEN DATOS'
      SET COLOR TO COLOR0
      INKEY(3)
      EXIT
   ENDIF
   STORE FECHA TO VFF
   MES=TMES(CMONTH(VFF))
   ANIO=ALLTRIM(STR(YEAR(VFF)))
   VFECMEN='Datos de Ventas de '+MES+' de '+ANIO
   LL=39-(LEN(VFECMEN)/2)
   SET COLOR TO COLOR3
   @2,10 TO 23,69 DOUBLE 
   SET COLOR TO COLOR6
   @4,17 SAY '  DATOS DE VENTAS ALMACENADOS EN EL DISKETTE  '
   SET COLOR TO COLOR0
   @6,11 to 6,68
   @17,11 to 17,68
   @18,11 CLEAR to 22,68
   @7,11 CLEAR TO 16,68
   @21,34 SAY '<   > Salir'
   SET COLOR TO COLOR3
   @19,LL SAY VFECMEN
   @21,35 SAY 'ESC'
   SET COLOR TO COLOR0
   SET CURSOR OFF
   CLEAR TYPEAHEAD
   DECLARE CAMP[11]
   CAMP[1]='FECHA'
   CAMP[2]='HORA'
   CAMP[3]='CODIGO'
   CAMP[4]='CANTIDAD'
   CAMP[5]='DETALLE'
   CAMP[6]='CODIGBARRA'
   CAMP[7]='PRECIO'
   CAMP[8]='SUBTOTAL'
   CAMP[9]='TOTAL'
   CAMP[10]='OPERADOR'
   CAMP[11]='NUMEROCAJA'
   DECLARE CABEZ[11]
   CABEZ[1]=' Fechas'
   CABEZ[2]='  Hora'
   CABEZ[3]='C¢digo'
   CABEZ[4]='Cant'
   CABEZ[5]='   Descripci¢n'
   CABEZ[6]='Cod. Barra'
   CABEZ[7]='P.Unit'
   CABEZ[8]='Sub Tot'
   CABEZ[9]='Total'
   CABEZ[10]='Operador de Turno'
   CABEZ[11]='N§ Caja'
   DECLARE SEPAR[11]
   SEPAR[1]='Ä'
   SEPAR[2]='Ä'
   SEPAR[3]='Ä'
   SEPAR[4]='Ä'
   SEPAR[5]='Ä'
   SEPAR[6]='Ä'
   SEPAR[7]='Ä'
   SEPAR[8]='Ä'
   SEPAR[9]='Ä'
   SEPAR[10]='Ä'
   SEPAR[11]='Ä'
   SET CURSOR OFF
   CLEAR TYPEAHEAD
   SET COLOR TO COLOR7
   DBEDIT(7,11,16,68,CAMP,'FUNMIA','',CABEZ,SEPAR)
   EXIT
ENDDO
CLOSE ALL
RUN CD.. >NUL
RUN DELTREE /Y .\CHURTI >NUL
RUN RD CHURTI >NUL
SET DEFAULT TO .\ESC
SET PATH TO .\ESC
RETURN

FUNCTION FUNMIA
PARAMETERS MODE
PUBLIC INTER
DO CASE
    CASE MODE=3
        TONE(500,2)
        SET COLOR TO COLOR0
        @13,29 TO 15,48
        @14,30 CLEAR TO 14,47
        SET COLOR TO COLOR9
        @14,31 SAY 'NO EXISTEN DATOS'
        SET COLOR TO COLOR0
        INKEY(3)
        RETURN(0)
    CASE MODE=1
        TONE(500,2)
        RETURN(1)
    CASE MODE=2
        TONE(500,2)
        RETURN(1)
    CASE MODE=0
        RETURN(1)
    CASE LASTKEY()=27
        RETURN(0)
    OTHERWISE
        RETURN(1)
ENDCASE
