#include "colores.ch"
@12,12 TO 14,66
@13,13 CLEAR TO 13,65
IF !FILE('.\ESC\PASS.OVL')
   TONE(500,2)
   SET COLOR TO COLOR8
   @13,23 SAY 'El Archivo de Clave NO EXISTE'
   INKEY(4)
   RETURN
ENDIF
TONE(500,2)
STORE SPACE(12) TO ACTCLAVE
SET COLOR TO COLOR10
@13,20 SAY 'Ingrese la Clave ACTUAL:'
SET COLOR TO N/N,N/N
@13,44 SAY ''GET ACTCLAVE PICTURE '@!'
READ
IF LASTKEY()=27.OR.ACTCLAVE=SPACE(12)
   RETURN
ENDIF
SET CURSOR OFF
XX=LEN(ALLTRIM(ACTCLAVE))
SET COLOR TO COLOR0
STORE FOPEN('.\ESC\PASS.OVL',2) TO CARAC
FSEEK (CARAC,0,0)
STORE FREADSTR(CARAC,XX) TO WORD
FCLOSE(CARAC)
STORE '' TO TMPCLAVE
FOR TT=1 TO XX
   STORE SUBSTR(ACTCLAVE,TT,1) TO ZZ
   STORE ASC(ZZ)+XX+90 TO YY
   STORE CHR(YY) TO ESTA
   TMPCLAVE=TMPCLAVE+ESTA
NEXT
STORE FOPEN('.\ESC\PASS.OVL',2) TO CARAC
STORE FREADSTR(CARAC,XX) TO LACLAVE
@13,13 CLEAR TO 13,65
IF LACLAVE<>TMPCLAVE.AND.XX<>0
   SET COLOR TO COLOR8
   @13,32 SAY 'Clave INCORRECTA'
   SET COLOR TO COLOR0
   TONE (1000,3)
   INKEY(3)
   RETURN
ENDIF
@13,13 CLEAR TO 13,65
TONE(500,2)
STORE SPACE(12) TO NVACLAVE
SET COLOR TO COLOR10
@13,22 SAY 'Ingrese nueva Clave:'
SET COLOR TO N/N,N/N
@13,44 SAY ''GET NVACLAVE PICTURE '@!'
READ
IF LASTKEY()=27
   RETURN
ENDIF
XX=LEN(ALLTRIM(NVACLAVE))
SET COLOR TO COLOR0
STORE FOPEN('.\ESC\PASS.OVL',2) TO CARAC
FSEEK (CARAC,0,0)
STORE FREADSTR(CARAC,XX) TO WORD
FCLOSE(CARAC)
STORE '' TO TMPCLAVE
FOR TT=1 TO XX
   STORE SUBSTR(NVACLAVE,TT,1) TO ZZ
   STORE ASC(ZZ)+XX+90 TO YY
   STORE CHR(YY) TO ESTA
   TMPCLAVE=TMPCLAVE+ESTA
NEXT
@13,13 CLEAR TO 13,65
TONE(500,2)
STORE SPACE(12) TO OTRACLAVE
SET COLOR TO COLOR10
@13,24 SAY 'REINGRESE LA CLAVE:'
SET COLOR TO N/N,N/N
@13,43 SAY ''GET OTRACLAVE PICTURE '@!'
READ
IF LASTKEY()=27
   RETURN
ENDIF
SET COLOR TO COLOR0
@13,13 CLEAR TO 13,65
IF OTRACLAVE<>NVACLAVE
   SET COLOR TO COLOR8
   @13,27 SAY 'CLAVE NUEVA NO RECONOCIDA'
   SET COLOR TO COLOR0
   TONE (1000,3)
   INKEY(3)
   RETURN
ENDIF
STORE FCREATE('.\ESC\PASS.OVL',0) TO CARAC
FWRITE(CARAC,TMPCLAVE)
FCLOSE(CARAC)
RETURN
