#include "colores.ch"
SAVE SCREEN TO CODIGSCR
SET CONFIRM OFF
SET CURSOR OFF

STORE 0 TO VCODIGO1,VCODIGO2
SET COLOR TO COLOR6
@3,48 SAY VCODIGO PICTURE '999999'

SET COLOR TO COLOR9
@12,30 SAY 'UN MOMENTO POR FAVOR'
SET COLOR TO COLOR0

IF VCODIGO=0
   USE MERCA
   INDEX ON DETALLE TO ORDDET
   GO TOP
   SAVE SCREEN TO JERI
   SET COLOR TO COLOR4
   @8,0 TO 23,79
   @9,1 CLEAR TO 22,78
   @21,1 TO 21,78
   @19,1 TO 19,78
   @20,1 CLEAR TO 20,78
   @22,1 CLEAR TO 22,78
   @22,11 SAY '        Tomar'
   @22,58 SAY '      Salir'
   SET COLOR TO COLOR10
   @20,28 SAY 'Fichero de Art¡culos'
   @22,11 SAY '<ENTER>'
   @22,58 SAY '<ESC>'

   DECLARE CAMP[3]
   CAMP[1]='CODIGO'
   CAMP[2]='left(DETALLE,50)'
   CAMP[3]='CONIVA'

   DECLARE CABEZ[3]
   CABEZ[1]='Codig'
   CABEZ[2]='                       Detalle'
   CABEZ[3]='Precios'

   DECLARE SEPAR[3]
   SEPAR[1]='Ä'
   SEPAR[2]='Ä'
   SEPAR[3]='Ä'
   SET CURSOR OFF
   CLEAR TYPEAHEAD

   SET COLOR TO COLOR6
   @24,1 SAY 'Buscar:                                                                       '
   SET COLOR TO COLOR7
   @12,30 SAY '                    '

   DBEDIT(9,1,18,78,CAMP,'FUNMOD','',CABEZ,SEPAR)
   RESTORE SCREEN FROM CODIGSCR

   IF LASTKEY()=27
      RETURN
   ENDIF

   STORE CODIGO TO VCODIGO
   STORE DETALLE TO VDETALLE
   STORE CODIGBARRA TO VBARRA
   STORE CONIVA TO VCONIVA
ELSE
   USE MERCA
   INDEX ON CODIGO TO ORDCOD
   GO TOP
   SEEK VCODIGO
   IF EOF()
      SET CURSOR OFF
      SET COLOR TO COLOR0
      @11,30 TO 13,52
      SET COLOR TO COLOR9
      @12,32 SAY 'CODIGO NO EXISTENTE'
      SET COLOR TO COLOR0
      TONE(1200,1)
      INKEY(3)
      STORE 0 TO VCANT
      STORE 0 TO VBARRA
      STORE 0 TO VCODIGO
      SET CURSOR ON
      RESTORE SCREEN FROM CODIGSCR
      RETURN
   ENDIF

   STORE CODIGO TO VCODIGO
   STORE DETALLE TO VDETALLE
   STORE CODIGBARRA TO VBARRA
   STORE CONIVA TO VCONIVA
ENDIF

USE STOCK
INDEX ON CODIGO TO ORDCODST
GO TOP

SEEK VCODIGO
IF EOF().OR.CANTIDAD=0
   SET CURSOR OFF
   SET COLOR TO COLOR0
   @11,30 TO 13,53
   SET COLOR TO COLOR9
   @12,32 SAY 'MERCADERIA SIN STOCK'
   SET COLOR TO COLOR0
   TONE(1200,1)
   INKEY(3)
   STORE 0 TO VBARRA
   RESTORE SCREEN FROM CODIGSCR
   RETURN
ENDIF

STORE CANTIDAD TO ENSTOCK,STACTUAL

SET COLOR TO COLOR3
@3,48 SAY VCODIGO PICTURE '@!'

SET COLOR TO COLOR0
@LINEA,5 SAY '³'
@LINEA,6 SAY LEFT(VDETALLE,50)
@LINEA,61 SAY '³'
@LINEA,62 SAY VCONIVA PICTURE '9999.99'
@LINEA,70 SAY '³'

SET COLOR TO COLOR3
@3,74 SAY STACTUAL PICTURE '9999'
SET COLOR TO COLOR0

DO WHILE .T.
   STORE 0 TO VCANT
   SET CURSOR ON
   @LINEA,0 SAY ''GET VCANT PICTURE '999'
   READ

   IF LASTKEY()=27
      RESTORE SCREEN FROM CODIGSCR
      RETURN
   ENDIF

   IF VCANT=0
      TONE(1200,1)
      LOOP
   ENDIF

   IF ENSTOCK<VCANT
      SET CURSOR OFF
      SAVE SCREEN TO YAMA
      SET COLOR TO COLOR0
      @11,20 TO 13,59
      @12,22 SAY 'La cantidad es SUPERIOR al stock'
      SET COLOR TO COLOR9
      @12,37 SAY 'SUPERIOR'
      SET COLOR TO COLOR0
      TONE(1200,1)
      INKEY(3)
      RESTORE SCREEN FROM YAMA
      LOOP
   ENDIF
   EXIT
ENDDO

STORE VCANT*VCONIVA TO VSUBTOT
@LINEA,72 SAY VSUBTOT PICTURE '9999.99'
STORE VTOTAL+VSUBTOT TO VTOTAL
SET COLOR TO COLOR3
@22,72 SAY VTOTAL PICTURE '9999.99'
SET COLOR TO COLOR0
LINEA=LINEA+1
@3,0 CLEAR TO 3,79

USE VTASTMP
APPEND BLANK
REPLACE FECHA WITH DATE()
REPLACE HORA WITH TIME()
REPLACE CODIGO WITH VCODIGO
REPLACE CANTIDAD WITH VCANT,DETALLE WITH VDETALLE,CODIGBARRA WITH VBARRA
REPLACE PRECIO WITH VCONIVA,SUBTOTAL WITH VSUBTOT,TOTAL WITH VTOTAL
REPLACE OPERADOR WITH NOMBOPER
RETURN
