CLEAR
STORE SPACE(60) TO VDETALLE
STORE 0 TO VCOSTO,VPUBLICO
SET KEY -1 TO INGFIRM
SET KEY -2 TO INGRUBR
STORE 0 TO TOMA1,TOMA2
USE MERCA
INDEX ON CODIGO TO ORDCOD
GO BOTTOM
STORE CODIGO+1 TO VCODMERC
DO WHILE .T.
   USE MERCA
   INDEX ON CODIGO TO ORDCOD
   GO BOTTOM
   STORE CODIGO+1 TO VCODMERC
   @0,0 TO 2,30
   SET COLOR TO BG+/B
   @1,2 SAY '* * * CENTRO PLASTICO * * *'
   numero=LEFT(DTOC(DATE()),2)
   DIA=TDIAS(cdow(DATE()))
   MES=TMES(CMONTH(DATE()))
   ANIO=ALLTRIM(STR(YEAR(DATE())))
   VFECHA=DIA+' '+numero+' de '+MES+' de '+ANIO
   LL=79-LEN(VFECHA)
   SET COLOR TO W+/B
   @1,LL-7 SAY 'Fecha: '
   @3,0 TO 5,39
   CARTEL='Art¡culo N§ '
   @4,44 SAY CARTEL
   SET COLOR TO BG+/B
   @4,3 SAY 'PANTALLA DE INGRESOS DE MERCADERIA'
   @1,LL SAY VFECHA
   @4,56 SAY ALLTRIM(STR(VCODMERC))
   SAVE SCREEN TO APOLO
   IF TOMA1=0
      DO INGFIRM
      IF LASTKEY()=27
         RETURN
      ENDIF
      TOMA1=1
   ENDIF
   RESTORE SCREEN FROM APOLO
   IF TOMA2=0
      DO INGRUBR
      IF LASTKEY()=27
         RETURN
      ENDIF
      TOMA2=1
   ENDIF
   RESTORE SCREEN FROM APOLO
   SET COLOR TO BG/B
   @7,1 SAY 'Firma:                                     Rubro:'
   SET COLOR TO W+/B
   @7,8 SAY LEFT(VFIRM,32)
   @7,51 SAY LEFT(VRUBR,28)
   @24,18 SAY '<F2> Cambiar la Firma     <F3> Cambiar el Rubro'
   SET COLOR TO BG+/B
   @6,0 SAY REPLICATE('Ä',79)
   @8,0 SAY REPLICATE('Ä',79)
   @24,19 SAY 'F2'
   @24,45 SAY 'F3'
   SET CURSOR ON
   @11,0 SAY REPLICATE('Ä',79)
   @13,0 SAY REPLICATE('Ä',79)
   @15,0 SAY REPLICATE('Ä',79)
   @17,0 SAY REPLICATE('Ä',79)
   SET COLOR TO W+/B,B/W
   @12,5 SAY 'Detalle:'GET VDETALLE PICTURE '@!K'
   @14,5 SAY 'Precio de Costo:'GET VCOSTO PICTURE '9999.99'
   @16,5 SAY 'Precio  P£blico:'GET VPUBLICO PICTURE '9999.99'
   SET COLOR TO W+/B
   SAVE SCREEN TO PANLISTO
   READ
   IF PULSO=1
      PULSO=0
      LOOP
   ENDIF
   IF LASTKEY()=27
      RETURN
   ENDIF
   USE MERCA
   INDEX ON DETALLE TO ORDDET
   GO TOP
   SEEK VDETALLE
   IF .NOT. EOF()
      SET CURSOR OFF
      TONE(1200,1)
      TONE(1200,1)
      TONE(1200,1)
      SET COLOR TO *R+/B
      @19,25 SAY 'El detalle de art¡culo ya EXISTE'
      SET COLOR TO W+/B
      STORE SPACE(60) TO VDETALLE
      INKEY(3)
      RESTORE SCREEN FROM PANLISTO
      LOOP
   ENDIF
   SET COLOR TO W+/B
   SET CURSOR OFF
   @21,25 SAY '¨ Guardar el art¡culo (S/N) ?'
   SET COLOR TO *R+/B
   @21,48 SAY 'S'
   @21,50 SAY 'N'
   SET COLOR TO W+/B
   DO WHILE .T.
      INKEY(0)
      IF LASTKEY()<>78.AND.LASTKEY()<>83.AND.LASTKEY()<>110.AND.LASTKEY()<>115
         TONE(500,1)
         LOOP
      ENDIF
      EXIT
   ENDDO
   IF LASTKEY()=83.OR.LASTKEY()=115
      APPEND BLANK
      REPLACE CODIGO WITH VCODMERC,DETALLE WITH VDETALLE,COSTO WITH VCOSTO
      REPLACE PUBLICO WITH VPUBLICO,FIRMA WITH VFIRM,RUBRO WITH VRUBR

      STORE 0 TO VCOSTO,VPUBLICO

      INDEX ON CODIGO TO ORDCOD
      GO BOTTOM
      STORE CODIGO+1 TO VCODMERC
   ENDIF
   RESTORE SCREEN FROM PANLISTO
   LOOP
ENDDO
