SAVE SCREEN TO TATY
DO WHILE .T.
   USE MERCA
   INDEX ON DETALLE TO ORDDET
   GO TOP
   SET COLOR TO BG/B
   @8,0 TO 23,79
   @24,0
   @9,1 CLEAR TO 22,78
   @21,1 TO 21,78
   @19,1 TO 19,78
   @20,1 CLEAR TO 20,78
   @22,1 CLEAR TO 22,78
   SET COLOR TO W+/B
   @22,11 SAY '        Tomar'
   @22,58 SAY '      Salir'
   SET COLOR TO BG+/B
   @20,28 SAY 'Fichero de Art¡culos'
   @22,11 SAY '<ENTER>'
   @22,58 SAY '<ESC>'
   DECLARE CAMP[2]
   CAMP[1]='DETALLE'
   CAMP[2]='PUBLICO'
   DECLARE CABEZ[2]
   CABEZ[1]='                       Detalle'
   CABEZ[2]='Precios'
   DECLARE SEPAR[2]
   SEPAR[1]='Ä'
   SEPAR[2]='Ä'
   SET CURSOR OFF
   CLEAR TYPEAHEAD
   SET COLOR TO B+/B
   @24,1 SAY 'Buscar:                                                                       '
   SET COLOR TO BG/B,B/W
   DBEDIT(9,1,18,78,CAMP,'FUNMOD','',CABEZ,SEPAR)
   IF LASTKEY()=27
      RESTORE SCREEN FROM TATY
      RETURN
   ENDIF
   STORE CODIGO TO VCODIGO
   STORE DETALLE TO VDETALLE
   STORE PUBLICO TO VPUBLICO
   STORE COSTO TO VCOSTO
   USE STOCK
   INDEX ON CODIGO TO ORDCODIG
   GO TOP
   SEEK VCODIGO
   STORE 0 TO VCANT
   IF EOF()
      EXISTE=0
      SET CURSOR OFF
      SET COLOR TO W+/B
      @11,30 TO 13,53
      SET COLOR TO *R+/B
      @12,32 SAY 'MERCADERIA SIN STOCK'
      SET COLOR TO W+/B
      TONE(1200,1)
      INKEY(3)
      STORE 0 TO VLIMI
   ELSE
      EXISTE=1
      STORE LIMITE TO VLIMI
      STORE CANTIDAD TO VCANT
   ENDIF
   SET COLOR TO W+/B
   CLEAR
   @0,0 TO 2,32
   @1,2 SAY 'CENTRO COMERCIAL DEL PLASTICO'
   numero=LEFT(DTOC(DATE()),2)
   DIA=TDIAS(cdow(DATE()))
   MES=TMES(CMONTH(DATE()))
   ANIO=ALLTRIM(STR(YEAR(DATE())))
   VFECHA=DIA+' '+numero+' de '+MES+' de '+ANIO
   LL=79-LEN(VFECHA)
   @1,LL-7 SAY 'Fecha: '
   SET COLOR TO BG+/B
   @1,LL SAY VFECHA
   SET CURSOR ON
   SET COLOR TO BG/B
   @6,0 SAY REPLICATE('Ä',79)
   SET CONFIRM OFF
   @7,1 SAY 'Detalle:'
   @9,1 SAY 'Precio de Venta:'
   @11,1 SAY 'Stock actual:'
   @13,1 SAY 'Ingrese nuevo Stock:'
   @15,1 SAY 'L¡mite de reposicion:'
   SET COLOR TO W+/B
   @7,10 SAY VDETALLE
   @9,18 SAY VPUBLICO
   SET COLOR TO *RG+/B
   IF EXISTE=0
      @11,15 SAY '0' PICTURE '9999.99'
   ELSE
      @11,15 SAY CANTIDAD PICTURE '9999.99'
   ENDIF
   SET COLOR TO BG/B
   @8,0 SAY REPLICATE('Ä',79)
   @10,0 SAY REPLICATE('Ä',79)
   @12,0 SAY REPLICATE('Ä',79)
   @14,0 SAY REPLICATE('Ä',79)
   @16,0 SAY REPLICATE('Ä',79)
   SET COLOR TO W+/B,B/W
   @13,21 SAY ''GET VCANT PICTURE '9999.99'
   @15,22 SAY ''GET VLIMI PICTURE '9999.99'
   READ
   IF LASTKEY()=27.OR.VCANT=0
      EXIT
   ENDIF
   SET CURSOR OFF
   SET COLOR TO W+/B
   @23,26 SAY '¨ Grabar este cambio (S/N) ?'
   SET COLOR TO *R+/B
   @23,48 SAY 'S'
   @23,50 SAY 'N'
   SET COLOR TO W+/B
   DO WHILE .T.
      INKEY(0)
      IF LASTKEY()<>78.AND.LASTKEY()<>83.AND.LASTKEY()<>110.AND.LASTKEY()<>115
         TONE(500,1)
         LOOP
      ENDIF
      EXIT
   ENDDO
   IF LASTKEY()=83.OR.LASTKEY()=115
      REPLACE CODIGO WITH VCODIGO,DETALLE WITH VDETALLE,PUBLICO WITH VPUBLICO
      REPLACE COSTO WITH VCOSTO,CANTIDAD WITH VCANT,LIMITE WITH VLIMI

   ENDIF
   RESTORE SCREEN FROM TATY
   LOOP
ENDDO
