SET COLOR TO W+/B
@12,12 TO 14,66
@13,13 CLEAR TO 13,65
IF !FILE('PASS.OVL')
   TONE(500,2)
   SET COLOR TO *R+/B
   @13,23 SAY 'El Archivo de Clave NO EXISTE'
   SET COLOR TO W+/B
   INKEY(4)
   RETURN
ENDIF
TONE(500,2)
SET COLOR TO W+/B
@13,22 SAY 'Ingrese la Clave ACTUAL :'
SET CURSOR OFF
STORE '' TO ESCLAVE
STORE 48 TO COLCL
STORE 0 TO SON
DO WHILE .T.
   INKEY(0)
   IF LASTKEY()=27
      RETURN
   ENDIF
   TONE (1800,1)
   @13,COLCL SAY '±'
   COLCL=COLCL+1
   IF LASTKEY()=13
      EXIT
   ENDIF
   SALE=1
   STORE CHR(LASTKEY()) TO ESTO
   ESCLAVE=ESCLAVE+ESTO
   SON=SON+1
ENDDO
XX=LEN(ALLTRIM(ESCLAVE))
STORE '' TO OTCLAVE
FOR TT=1 TO XX
   STORE SUBSTR(ESCLAVE,TT,1) TO ZZ
   STORE ASC(ZZ)+XX+90 TO YY
   STORE CHR(YY) TO ESTA
   OTCLAVE=OTCLAVE+ESTA
NEXT
ESCLAVE=OTCLAVE
STORE FOPEN('PASS.OVL',2) TO CARAC
STORE FREADSTR(CARAC,XX) TO LACLAVE
@13,13 CLEAR TO 13,65
IF LACLAVE<>ESCLAVE.AND.SON<>0
   SET COLOR TO *R+/B
   @13,32 SAY 'Clave INCORRECTA'
   SET COLOR TO W+/B
   TONE (1000,3)
   INKEY(3)
   RETURN
ENDIF
SET COLOR TO W+/B
@13,13 CLEAR TO 13,65
TONE(500,2)
SET CURSOR OFF
STORE '' TO ESCLAVE
@13,26 SAY 'Ingrese nueva Clave: '
STORE 47 TO COLCL
DO WHILE .T.
   INKEY(0)
   IF LASTKEY()=27
      RETURN
   ENDIF
   TONE (1800,1)
   @13,COLCL SAY '±'
   COLCL=COLCL+1
   IF LASTKEY()=13
      EXIT
   ENDIF
   SALE=1
   STORE CHR(LASTKEY()) TO ESTO
   ESCLAVE=ESCLAVE+ESTO
   SON=SON+1
ENDDO
@13,13 CLEAR TO 13,65
TONE(500,2)
SET CURSOR OFF
STORE '' TO OTRACLAVE
@13,24 SAY 'REINGRESE LA CLAVE: '
STORE 44 TO COLCL
DO WHILE .T.
   INKEY(0)
   IF LASTKEY()=27
      RETURN
   ENDIF
   TONE (1800,1)
   @13,COLCL SAY '±'
   COLCL=COLCL+1
   IF LASTKEY()=13
      EXIT
   ENDIF
   STORE CHR(LASTKEY()) TO ESTO
   OTRACLAVE=OTRACLAVE+ESTO
ENDDO
@13,13 CLEAR TO 13,65
IF OTRACLAVE<>ESCLAVE
   SET COLOR TO *R+/B
   @13,27 SAY 'CLAVE NUEVA NO RECONOCIDA'
   TONE (1000,3)
   INKEY(3)
   RETURN
ENDIF
XX=LEN(ALLTRIM(OTRACLAVE))
STORE '' TO CLAVE
FOR TT=1 TO XX
   STORE SUBSTR(OTRACLAVE,TT,1) TO ZZ
   STORE ASC(ZZ)+XX+90 TO YY
   STORE CHR(YY) TO ESTA
   CLAVE=CLAVE+ESTA
NEXT
STORE FCREATE('PASS.OVL',0) TO CARAC
FWRITE(CARAC,CLAVE)
FCLOSE(CARAC)
RETURN
