SET COLOR TO W+/B
@12,12 TO 14,66
@13,13 CLEAR TO 13,65
IF !FILE('PASS.OVL')
   TONE(500,2)
   SET COLOR TO *R+/B
   @13,23 SAY 'El Archivo de Clave NO EXISTE'
   SET COLOR TO W+/B
   INKEY(4)
   RETURN
ENDIF
TONE(500,2)
SET CURSOR OFF
STORE '' TO ESCLAVE
SET COLOR TO W+/B
@13,29 SAY 'Ingrese Clave: '
STORE 44 TO COLCL
STORE 0 TO SON
DO WHILE .T.
   INKEY(0)
   IF LASTKEY()=27
      RETURN
   ENDIF
   TONE (1800,1)
   @13,COLCL SAY '±'
   COLCL=COLCL+1
   IF LASTKEY()=13
      EXIT
   ENDIF
   SALE=1
   STORE CHR(LASTKEY()) TO ESTO
   ESCLAVE=ESCLAVE+ESTO
   SON=SON+1
ENDDO
STORE '' TO WORD
CUAN=LEN(ESCLAVE)
STORE FOPEN('PASS.OVL',2) TO CARAC
FSEEK (CARAC,0,0)
STORE FREADSTR(CARAC,CUAN) TO WORD
FCLOSE(CARAC)
XX=LEN(ESCLAVE)
STORE '' TO CLAVE
FOR TT=1 TO XX
   STORE SUBSTR(ESCLAVE,TT,1) TO ZZ
   STORE ASC(ZZ)+XX+90 TO YY
   STORE CHR(YY) TO ESTA
   CLAVE=CLAVE+ESTA
NEXT
STORE CLAVE TO ESCLAVE
@13,13 CLEAR TO 13,65
IF WORD=ESCLAVE.AND.SON<>0
   TONE (1000,3)
   STORE 1 TO CORRECTO
ELSE
   SET COLOR TO *R+/B
   @13,32 SAY 'Clave INCORRECTA'
   SET COLOR TO W+/B
   TONE (1000,3)
   INKEY(3)
   STORE 0 TO CORRECTO
ENDIF
SET COLOR TO W+/B
RETURN
