IF VIVA='RI'
   STORE 3 TO CPRIN
ELSE
   STORE 2 TO CPRIN
ENDIF

*****
STORE 1 TO CPRIN
*****

SET CURSOR OFF
DO WHILE .T.
   SET COLOR TO W+/B
   @22,16 CLEAR TO 24,61 
   @22,16 TO 24,61 
   @23,21 SAY 'Prepare la Impresora y pulse <ENTER>'
   SET COLOR TO BG+/B
   @23,51 SAY 'ENTER'
   SET COLOR TO W+/B
   INKEY(0)
   IF LASTKEY()=27
      RETURN
   ENDIF
   IF ISPRINTER()
      EXIT
   ELSE
      TONE(500,2)
      @23,17 CLEAR TO 23,60 
      SET COLOR TO W+/B
      @23,20 SAY 'La Impresora NO ESTA LISTA...'
      SET COLOR TO *R+/B
      @23,49 SAY 'VERIFIQUE'
      INKEY(3)
      SET COLOR TO W+/B
      LOOP
   ENDIF
ENDDO
SET COLOR TO W+/B
@23,17 CLEAR TO 23,60
SET CURSOR OFF
SET COLOR TO *RG+/B
@23,24 SAY 'ESTOY IMPRIMIENDO....­ ESPERATE !'
SET COLOR TO W+/B
SET DEVICE TO PRINT
IF VIVA='RI'
   USE FACT_A
   COPY TO VTASTMP FOR NUMERO=NUMFA
ELSE
   USE FACT_B
   COPY TO VTASTMP FOR NUMERO=NUMFB
ENDIF
USE VTASTMP
GO TOP
FOR K=1 TO CPRIN
   STORE 0 TO TTT
   @2,54 SAY DATE()
   @8,12 SAY VNOMBRE
   @10,12 SAY VDOMI
   IF VIVA='RI'
      VVI='RESPONSABLE INSCRIPTO'
   ELSEIF VIVA='NR'
      VVI='NO RESPONSABLE'
   ELSEIF VIVA='MT'
      VVI='MONOTRIBUTISTA'
   ELSEIF VIVA='EX'
      VVI='EXENTO'
   ELSE
      VVI='CONSUMIDOR FINAL'
   ENDIF
   @12,12 SAY VVI
   @12,56 SAY VCUIT PICTURE '99-99999999-9'
   @13,17 SAY 'CONTADO'
   USE VTASTMP
   GO TOP
   STORE 16 TO LINEA
   DO WHILE .T.
      IF EOF()
         EXIT
      ENDIF
      @LINEA,2 SAY CANTIDAD PICTURE '9999.99'
      @LINEA,20 SAY ALLTRIM(DETALLE)
      @LINEA,63 SAY PRECIO PICTURE '9999.99'
      @LINEA,73 SAY TOTAL PICTURE '9999.99'
      STORE TTT+TOTAL TO TTT
      LINEA=LINEA+1
      SKIP
      LOOP
   ENDDO
   IF VIVA='RI'
      NETO=TTT/1.21
      IMPUESTO=TTT-NETO
      TOTALTOTAL=NETO+IMPUESTO
      @30,7 SAY NETO PICTURE '9999.99'
      @30,33 SAY NETO PICTURE '9999.99'
      @30,46 SAY IMPUESTO PICTURE '9999.99'
      @30,73 SAY TOTALTOTAL PICTURE '9999.99'
   ELSE
      @30,73 SAY TTT PICTURE '9999.99'
   ENDIF
   EJECT
NEXT
SET DEVICE TO SCREEN
RETURN
