CLEAR
SET CENTURY ON
SET DATE TO FRENCH
DO WHILE .T.
   SET COLOR TO BG/B
   @16,15 TO 20,65
   @17,16 CLEAR TO 19,64
   SET COLOR TO W+/B
   SET COLOR TO W+/B
   @17,18 SAY 'Desde Fecha:            Hasta Fecha:'
   @19,28 SAY 'Pulse <ENTER> para tomar todo'
   SET COLOR TO B/W
   @17,55 SAY '  /  /    '
   SET COLOR TO *BG+/B
   @19,35 SAY 'ENTER'
   SET CURSOR ON
   STORE CTOD('  /  /    ') TO DESDE,HASTA
   SET COLOR TO BG/B,B/W
   @17,30 SAY ''GET DESDE PICTURE '99/99/9999'
   READ
   IF LASTKEY()=27
      RETURN
   ENDIF
   IF DESDE=CTOD('  /  /    ')
      SET CURSOR OFF
      STORE CTOD('01/01/80') TO DESDE
      STORE DATE() TO HASTA
      @19,16 CLEAR TO 19,64
      SET COLOR TO *BG+/B
      @19,34 SAY 'Tomando TODO'
      SET COLOR TO
      INKEY(1)
   ELSE
      @19,16 CLEAR TO 19,64
      SET COLOR TO *BG+/B
      @19,32 SAY 'Tomando FRACCION'
      SET COLOR TO BG/B,B/W
      @17,54 SAY ''GET HASTA PICTURE '99/99/99'
      READ
      IF HASTA=CTOD('  /  /    ')
         STORE DATE() TO HASTA
      ENDIF
   ENDIF
   SET CURSOR OFF
   IF DESDE>HASTA
      TONE(1200,1)
      SET COLOR TO *R+/B
      @19,16 CLEAR TO 19,64
      @19,34 SAY 'Mal Ingresado'
      SET COLOR TO W+/B
      SET CURSOR OFF
      INKEY(1)
      @19,16 CLEAR TO 19,64
      LOOP
   ENDIF
   EXIT
ENDDO

USE FACT_A
INDEX ON FECHA TO ORDFEC
SET FILTER TO FECHA>=DESDE.AND.FECHA<=HASTA
GO TOP
COPY TO FA
CLOSE ALL
USE FACT_A
DELETE ALL FOR FECHA>=DESDE.AND.FECHA<=HASTA


USE FACT_B
INDEX ON FECHA TO ORDFEC
SET FILTER TO FECHA>=DESDE.AND.FECHA<=HASTA
GO TOP
COPY TO FB
CLOSE ALL
USE FACT_B
DELETE ALL FOR FECHA>=DESDE.AND.FECHA<=HASTA

