#include "colores.ch"
USE ACTUAL
INDEX ON OPERADOR TO INDXNOM
GO TOP
IF HIZOCAJA<>'S'
   TONE(500,2)
   SET COLOR TO COLOR4
   @13,13 CLEAR TO 13,65
   SET COLOR TO COLOR8
   @13,22 SAY 'PRIMERO DEBE REALIZAR LA CAJA ACTUAL'
   SET COLOR TO COLOR0
   INKEY(5)
*   RETURN
ENDIF
CLEAR
SET COLOR TO COLOR3
@1,0 SAY 'ESTACION DE SERVICIO CENTRO'
numero=LEFT(DTOC(DATE()),2)
DIA=TDIAS(cdow(DATE()))
MES=TMES(CMONTH(DATE()))
ANIO=ALLTRIM(STR(YEAR(DATE())))
VFECHA=DIA+' '+numero+' de '+MES+' de '+ANIO
LL=79-LEN(VFECHA)
SET COLOR TO COLOR0
@1,LL SAY VFECHA
@2,0 SAY REPLICATE('Ä',27)
@2,LL SAY REPLICATE('Ä',LEN(VFECHA))
@3,25 TO 5,48
SET COLOR TO COLOR9
@4,28 SAY 'AGREGADOS DE CAJAS'
SET COLOR TO COLOR0
USE BASECAJA
INDEX ON NUMEROCAJA TO ORDCAJA
GO BOTTOM
STORE NUMEROCAJA+1 TO NUMACT
SAVE SCREEN TO ANITA
DO WHILE .T.
   STORE ENCAJA TO SALDOCAJA
   STORE OPERADOR TO OPERANTERIOR
   X1=LEN(ALLTRIM(OPERANTERIOR))
   SET COLOR TO COLOR0
   @10,4 SAY 'Dejado por '
   @10,16+X1 SAY 'en turno anterior '
   @10,33+X1 SAY REPLICATE('.',33-X1)
   @10,66 SAY '$ '
   SET COLOR TO COLOR3
   @10,15 SAY ALLTRIM(OPERANTERIOR)
   SET COLOR TO COLOR6
   @10,68 SAY SALDOCAJA PICTURE '9999.999'
   SET COLOR TO COLOR0
   STORE 0 TO TVENTAS,TGASTOS,TEXISTE
   SET CURSOR ON
   @14,4 SAY 'Total de ventas...............................................$'GET TVENTAS PICTURE '9999.999'RANGE 0,9999.999
   @16,4 SAY 'Total de gastos varios........................................$'GET TGASTOS PICTURE '9999.999'RANGE 0,9999.999
   @18,4 SAY 'Dinero existente en caja......................................$'GET TEXISTE PICTURE '9999.999'RANGE 0,9999.999
   READ
   IF LASTKEY()=27
      RETURN
   ENDIF
   TDEBERIA=TEXISTE
   SET COLOR TO COLOR0
   @24,29 SAY '¨ Realiza Caja (S/N) ?'
   SET COLOR TO COLOR3
   @24,45 SAY 'S'
   @24,47 SAY 'N'
   SET COLOR TO COLOR0
   SET CURSOR OFF
   DO WHILE .T.
      INKEY(0)
      IF LASTKEY()<>83.AND.LASTKEY()<>115.AND.LASTKEY()<>78.AND.LASTKEY()<>110
         TONE(1200,1)
         LOOP
      ENDIF
      EXIT
   ENDDO
   @24,0
   IF LASTKEY()=83.OR.LASTKEY()=115
      STORE '00000' TO CLOP
      STORE 'CAJA AGREGADA' TO NOMBOPER

      APPEND BLANK
      REPLACE FECHA WITH DATE(),HORA WITH TIME(),PASWORD WITH CLOP
      REPLACE OPERADOR WITH NOMBOPER,TOTVENTAS WITH TVENTAS,TOTGASTOS WITH TGASTOS
      REPLACE ENCAJA WITH TEXISTE,DEBERIA WITH TDEBERIA,NUMEROCAJA WITH NUMACT

      USE ACTUAL
      GO TOP
      REPLACE NUMEROCAJA WITH NUMACT,OPERADOR WITH NOMBOPER,PASWORD WITH CLOP
      REPLACE FECHA WITH DATE(),HORA WITH TIME(),HIZOCAJA WITH 'S'

      EXIT
   ENDIF
   RESTORE SCREEN FROM ANITA
   LOOP
ENDDO
RETURN
