#include "colores.ch"

PUBLIC VTOT_GASTOS
PUBLIC VOPERA
PUBLIC VTOT_SUBTOT
PUBLIC VINICIAL
PUBLIC VHORAIN

set color to b
@11,15 TO 23,55
@12,16 CLEAR TO 21,54
@21,16 TO 23,54
@22,17 CLEAR TO 22,53

set color to w
@22,26 SAY 'Tomar'
@22,48 SAY 'Salir'

SET COLOR TO w+
@22,18 SAY '<ENTER>'
@22,42 SAY '<ESC>'

USE .\ESC\VTASPEND
INDEX ON OPERADOR TO .\ESC\VTASPEND UNIQUE
GO TOP

if eof()
  return
endif

DECLARE CAMP[1]
CAMP[1]='OPERADOR'

DECLARE CABEZ[1]
CABEZ[1]=' OPERADOR'

DECLARE SEPAR[1]
SEPAR[1]='Ä'

SET CURSOR OFF
CLEAR TYPEAHEAD
SET COLOR TO COLOR7
DBEDIT(12,17,20,54,CAMP,'','',CABEZ,SEPAR)

IF LASTKEY()=27
   RETURN
ENDIF

STORE OPERADOR TO VOPERA

STORE 0 TO ID_CLASIFICACION
STORE SPACE(20) TO vclasificacion
PUBLIC ID_CLASIFICACION,vclasificacion
DO CLAS_LIS

USE .\ESC\VTASPEND
INDEX ON OPERADOR TO .\ESC\VTASPEND
SET FILTER TO OPERADOR=VOPERA

GO TOP
SUM SUBTOTAL TO VTOT_SUBTOT

if ID_CLASIFICACION=0
   store VTOT_SUBTOT to VTOT_CLASIFICACION
else
   GO TOP
   SET FILTER TO IDCLASIFIC=ID_CLASIFICACION
   SUM SUBTOTAL TO VTOT_CLASIFICACION
endif

USE .\ESC\GTOSPEND
SET FILTER TO OPERADOR=VOPERA
INDEX ON OPERADOR TO .\ESC\GTOSPEND
GO TOP
SUM VALOR TO VTOT_GASTOS

use .\ESC\ACTUAL
GO TOP
STORE INICIAL TO VINICIAL   
STORE HORA TO VHORAAP

DO RINDECAJ
* rindecaj devuelve VGRB_CAJA 0 1

IF VGRB_CAJA=1
   ACTUALIZA_BASES()
ENDIF

FUNCTION ACTUALIZA_BASES()
    USE .\ESC\VENTAS
    APPEND FROM .\ESC\VTASPEND FOR OPERADOR=VOPERA

    USE .\ESC\VTASPEND
    INDEX ON OPERADOR TO .\ESC\VTASPEND
    SET FILTER TO OPERADOR=VOPERA
    GO TOP
    delete all
    pack

    USE .\ESC\GTOSPEND
    SET FILTER TO OPERADOR=VOPERA
    INDEX ON OPERADOR TO .\ESC\GTOSPEND
    GO TOP
    delete all
    pack

    use .\ESC\VTANRO
    go top
    store 0 to VVTANRO
    REPLACE VTANRO WITH VVTANRO

    use .\ESC\ACTUAL
    ZAP
RETURN NIL


