#include "colores.ch"
SAVE SCREEN TO AA
DO BACKUPVT

VERIFICA_OP()

SET KEY -2 TO BORRALIN
PUBLIC NOMBOPER,NUMACT,HIZO,F_ACTUAL,H_ACTUAL

USE ACTUAL
INDEX ON OPERADOR TO INDXNOM
GO TOP
STORE OPERADOR TO NOMBOPER

RESTORE SCREEN FROM AA

CLEAR
SET COLOR TO B
@0,0, 24,79 BOX 'ÛÛÛÛÛÛÛÛÛ'
STORE 0 TO AGAST
SET COLOR TO LETRASC1
@1,0 SAY 'ESTACION DE SERVICIO CENTRO'
numero=LEFT(DTOC(DATE()),2)
DIA=TDIAS(cdow(DATE()))
MES=TMES(CMONTH(DATE()))
ANIO=ALLTRIM(STR(YEAR(DATE())))
VFECHA=DIA+' '+numero+' de '+MES+' de '+ANIO
LL=79-LEN(VFECHA)

SET COLOR TO LETRASC1
@1,LL SAY VFECHA
@2,0 SAY REPLICATE('Ä',27)
@2,LL SAY REPLICATE('Ä',LEN(VFECHA))
@0,32 TO 2,41

SET COLOR TO LETRASC0
@1,34 SAY 'VENTAS'

SET COLOR TO LETRASC0
@5,0 SAY 'Cant.                         Detalle                         P.Unit.   P.Total'

SET COLOR TO COLOR0
@5,5 SAY '³'
@5,61 SAY '³'
@5,70 SAY '³'
@4,0 SAY REPLICATE('Ä',79)
@6,0 SAY REPLICATE('Ä',79)
STORE 7 TO LINEA
STORE 0 TO VTOTAL
@21,0 SAY REPLICATE('Ä',79)
@22,7 SAY 'Eliminar rengl¢n'
@22,48 SAY 'TOTAL VENTA'
@23,0 SAY REPLICATE('Ä',79)
@24,2 SAY '<ESC> Salir/Guardar'
@24,30 SAY 'Operador de turno:'

SET COLOR TO LETRASC1
@22,2 SAY '<F3>'
@24,2 SAY '<ESC>'
@24,49 SAY NOMBOPER

SET COLOR TO COLOR0
SAVE SCREEN TO INICIO

SET CURSOR OFF
SET COLOR TO COLOR0
@11,30 TO 13,53
SET COLOR TO COLOR9
@12,32 SAY 'UN MOMENTO POR FAVOR'
SET COLOR TO COLOR0
TONE(1200,1)

USE MERCA
INDEX ON CODIGBARRA TO ORDBARRA
INDEX ON DETALLE TO ORDDET
INDEX ON CODIGO TO ORDCOD
GO TOP

USE STOCK
INDEX ON CODIGO TO ORDCODST
GO TOP

RESTORE SCREEN FROM INICIO

DO WHILE .T.
   SET COLOR TO LETRASC0
   @3,0 SAY 'C¢d.Barra:'
   @3,40 SAY 'C¢digo:'
   @3,64 SAY 'En stock:'

   STORE 0 TO VBARRA
   STORE 0 TO VCODIGO

   SET CURSOR ON
   SET COLOR TO COLOR4
   @3,10 SAY ''GET VBARRA PICTURE '99999999999999'
   READ
   PANTALLA=SAVESCREEN(17,0,24,79)

   IF AGAST=1
      STORE 0 TO AGAST
      LOOP
   ENDIF

   IF LASTKEY()=27
      IF LINEA>7
         STORE 7 TO LINEA
         STORE 0 TO VTOTAL
         @24,0
         SET CURSOR OFF
         SET COLOR TO LETRASC0
         @24,21  SAY '¨ Guardar y emitir el comprobante (S/N) ?'
         SET COLOR TO LETRASC1
         @24,56  SAY 'S'
         @24,58  SAY 'N'
         SET COLOR TO COLOR0
         TONE(1200,1)

            INKEY(0)
                        
         IF LASTKEY()=83.OR.LASTKEY()=115
               TONE(1200,1)                                            
                        
            DESC_STOCK()
                        
            SET FILTER TO
            @24,0
            SET CURSOR OFF
            SET COLOR TO LETRASC0
            @24,25  SAY '¨ Imprimir el comprobante (S/N) ?'
            SET COLOR TO LETRASC1
            @24,52  SAY 'S'
            @24,54  SAY 'N'
            SET COLOR TO COLOR0
            TONE(1200,1)
            INKEY(0)
            @24,0

            IF LASTKEY()=83.OR.LASTKEY()=115
               TONE(1200,1)                                            
               DO PRNCOMPR
               STORE 7 TO LINEA
               STORE 0 TO VTOTAL
            ENDIF

            USE VTASPEND
            APPEND FROM VTASTMP

            USE VTASTMP
            ZAP

            use .\ESC\VTANRO
            STORE VTANRO+1 TO VVTANRO
            REPLACE VTANRO WITH VVTANRO

            RESTORE SCREEN FROM INICIO

            LOOP
         ENDIF
         STORE 7 TO LINEA
         STORE 0 TO VTOTAL

         USE VTASTMP
         ZAP

         RESTORE SCREEN FROM INICIO
         LOOP
      ENDIF
      SET KEY -2 TO
      RETURN
   ENDIF

   IF VBARRA=0
      DO VTACODIG
   ELSE
      DO VTABARRA
   ENDIF

   LOOP
ENDDO

PROCEDURE BORRALIN
SAVE SCREEN TO TATYANA
STORE 1 TO AGAST
@16,0 TO 23,79
@24,0 CLEAR TO 24,79
SET COLOR TO COLOR0
@24,31 SAY '<ENTER> para borrar'
SET COLOR TO LETRASC1
@24,31 SAY '<ENTER>'
SET COLOR TO COLOR0

USE VTASTMP
GO TOP

DECLARE CAMP[4]
CAMP[1]='CANTIDAD'
CAMP[2]='DETALLE'
CAMP[3]='PRECIO'
CAMP[4]='SUBTOTAL'

DECLARE CABEZ[4]
CABEZ[1]='Cant'
CABEZ[2]='         Detalle'
CABEZ[3]='Precio'
CABEZ[4]='SubTot'

DECLARE SEPAR[4]
SEPAR[1]='Ä'
SEPAR[2]='Ä'
SEPAR[3]='Ä'
SEPAR[4]='Ä'

SET CURSOR OFF
CLEAR TYPEAHEAD
SET COLOR TO COLOR7
DBEDIT(17,1,22,78,CAMP,'','',CABEZ,SEPAR)
RESTORE SCREEN FROM TATYANA

IF LASTKEY()=13
   STORE LINEA-1 TO LINEA
   STORE RECNO() TO NUMLIN
   STORE SUBTOTAL TO VSUB
   STORE CODIGO TO VCODIGO

   DELETE
   PACK
   GO TOP

   STORE LASTREC() TO CUANTOS
   @7,0 CLEAR TO 20,79
   RESTSCREEN(17,0,24,79,PANTALLA)

   FOR FGH=1 TO CUANTOS
      SET COLOR TO LETRASC0
      @6+FGH,1 SAY CANTIDAD PICTURE '999'
      SET COLOR TO COLOR0
      @6+FGH,5 SAY '³'
      @6+FGH,6 SAY LEFT(DETALLE,50)
      @6+FGH,61 SAY '³'
      @6+FGH,62 SAY PRECIO PICTURE '9999.999'
      @6+FGH,70 SAY '³'
      SET COLOR TO LETRASC0
      XTOTAL=CANTIDAD*PRECIO
      @6+FGH,72 SAY XTOTAL PICTURE '9999.99'
      SET COLOR TO COLOR0
      REPLACE TOTAL WITH XTOTAL
      SKIP
   NEXT

   SUM TOTAL TO VTOTAL
   @22,72 CLEAR TO 22,79
   SET COLOR TO LETRASC1
   @22,72 SAY VTOTAL PICTURE '9999.999'
   SET COLOR TO COLOR0
   USE STOCK INDEX ORDCODST
   GO TOP
   SEEK VCODIGO
ENDIF
SET CURSOR ON
KEYBOARD CHR(13)

RETURN



FUNCTION DESC_STOCK

STORE 0 TO VCANT2
STORE 0 TO VTT
STORE 1 TO IR
STORE 0 TO SALE

USE .\ESC\STOCK
INDEX ON CODIGO TO ORDCODST
GO TOP

DO WHILE.T.
  USE .\ESC\VTASTMP
  GO IR
  STORE CODIGO TO VCOD
  STORE CANTIDAD TO VCANT

  IF EOF()=.T.
    STORE 1 TO SALE
  ENDIF

  USE .\ESC\STOCK
  SET INDEX TO ORDCODST
  GO TOP
  SEEK VCOD

  IF FOUND()=.T.
     STORE CANTIDAD TO VCANT2
     STORE VCANT2-VCANT TO VTT
     REPLACE CANTIDAD WITH VTT
  ELSE
  ENDIF

  IF SALE=1
    USE .\ESC\STOCK
    SET INDEX TO ORDCODST
    REINDEX
    EXIT
  ENDIF

  STORE IR+1 TO IR
LOOP
ENDDO
RETURN NIL
