#include "colores.ch"
SAVE SCREEN TO TATITA
DO WHILE .T.
   STORE DATE() TO DESDE,HASTA
   SET CURSOR ON
   SET COLOR TO COLOR3
   @16,14 TO 20,64 DOUBLE
   @17,15 CLEAR TO 19,63
   SET COLOR TO SELECT1
   @17,17 SAY 'Desde Fecha:            Hasta Fecha:'
   @19,26 SAY 'Pulse <ENTER> para tomar todo'
   SET COLOR TO COLOR9
   @19,32 SAY '<ENTER>'
   SET COLOR TO COLOR0
   @17,29 SAY ''GET DESDE PICTURE '99/99/99'
   READ
   IF LASTKEY()=27
      RETURN
   ENDIF
   IF DESDE=CTOD('  /  /  ')
      SET CURSOR OFF
      @17,15 CLEAR TO 19,63
      SET COLOR TO COLOR9
      @17,35 SAY 'Tomando TODO'
      SET COLOR TO COLOR0
      STORE CTOD('01/01/80') TO DESDE
      STORE DATE() TO HASTA
   ELSE
      @19,15 CLEAR TO 19,63
      SET COLOR TO COLOR9
      @19,33 SAY 'Tomando FRACCION'
      SET COLOR TO COLOR0
      @17,53 SAY ''GET HASTA PICTURE '99/99/99'
      READ
   ENDIF
   IF DESDE>HASTA
      TONE(1200,1)
      LOOP
   ENDIF
   SET CURSOR OFF
   EXIT
ENDDO

USE VENTAS
INDEX ON FECHA TO ORDFEC
GO TOP
SET FILTER TO FECHA>=DESDE.AND.FECHA<=HASTA
GO TOP

CLEAR
SET COLOR TO COLOR0
@0,22 TO 2,57
SET COLOR TO COLOR3
@1,25 SAY 'PANTALLA DE LISTADOS DE VENTAS'
SET COLOR TO COLOR4
@4,0 TO 22,79
@5,1 CLEAR TO 21,78
@18,1 TO 18,77
@20,1 TO 20,77
@21,35 SAY '      Salir'
SET COLOR TO COLOR10
@19,32 SAY 'Fichero de Ventas'
@21,35 SAY '<ESC>'

DECLARE CAMP[10]
CAMP[1]='FECHA'
CAMP[2]='HORA'
CAMP[3]='CODIGBARRA'
CAMP[4]='CODIGO'
CAMP[5]='CANTIDAD'
CAMP[6]='DETALLE'
CAMP[7]='PRECIO'
CAMP[8]='SUBTOTAL'
CAMP[9]='TOTAL'
CAMP[10]='OPERADOR'

DECLARE CABEZ[10]
CABEZ[1]=' Fecha'
CABEZ[2]=' Hora'
CABEZ[3]=' Codigo de Barra'
CABEZ[4]=' Codigo'
CABEZ[5]=' Cantidad'
CABEZ[6]='         Detalle'
CABEZ[7]='Importe'
CABEZ[8]=' Subtotal'
CABEZ[9]=' Total'
CABEZ[10]='         Operador de turno'

DECLARE SEPAR[10]
SEPAR[1]='Ä'
SEPAR[2]='Ä'
SEPAR[3]='Ä'
SEPAR[4]='Ä'
SEPAR[5]='Ä'
SEPAR[6]='Ä'
SEPAR[7]='Ä'
SEPAR[8]='Ä'
SEPAR[9]='Ä'
SEPAR[10]='Ä'

SET CURSOR OFF
CLEAR TYPEAHEAD
SET COLOR TO COLOR7
DBEDIT(5,1,17,78,CAMP,'FUNVTA','',CABEZ,SEPAR)
SET FILTER TO

IF LASTKEY()=27
   RETURN
ENDIF

IF LASTKEY()=13
   STORE RECNO() TO REGISTRO
   SET COLOR TO COLOR0
   @5,1 CLEAR TO 21,78
   @0,0 CLEAR TO 2,79
   @0,22 TO 2,57
   SET COLOR TO COLOR3
   @1,25 SAY 'PANTALLA MODIFICACIONES VENTAS'
   SET COLOR TO COLOR0
   SET CURSOR ON

   STORE FECHA TO VFEC
   STORE HORA TO VHOR
   STORE OPERADOR TO VOPER
   STORE CODIGBARRA TO VCODB_OR
   STORE CODIGO TO VCODI_OR
   STORE CANTIDAD TO VCANT_OR
   STORE DETALLE TO VDET_OR
   STORE PRECIO TO VPRE_OR
   STORE SUBTOTAL TO VSUB_OR
   STORE TOTAL TO VTOT_OR

   @6,2 SAY 'FechaÄÄÄÄÄÄÄÄ>: '
   @8,2 SAY 'HoraÄÄÄÄÄÄÄÄÄ>: '
   SET COLOR TO COLOR6
   @6,18 SAY DTOC(VFEC)
   @8,18 SAY VHOR
   SET COLOR TO COLOR0

   USE MERCA
   INDEX ON CODIGO TO ORDCOD
   INDEX ON DETALLE TO ORDDET
   GO TOP

   SAVE SCREEN TO JERI
   SET COLOR TO COLOR0
   @8,0 TO 23,79
   @9,1 CLEAR TO 22,78
   @21,1 TO 21,78
   @19,1 TO 19,78
   @20,1 CLEAR TO 20,78
   @22,1 CLEAR TO 22,78
   @22,09 SAY '        Tomar Nuevo'
   @22,48 SAY '      Salir/Dejar actual'
   SET COLOR TO COLOR10
   @20,28 SAY 'Fichero de Art¡culos'
   @22,09 SAY '<ENTER>'
   @22,48 SAY '<ESC>'

   DECLARE CAMP2[3]
   CAMP2[1]='CODIGO'
   CAMP2[2]='left(DETALLE,50)'
   CAMP2[3]='PCOSTO'

   DECLARE CABEZ2[3]
   CABEZ2[1]='Codig'
   CABEZ2[2]='                       Detalle'
   CABEZ2[3]='Precios'

   DECLARE SEPAR2[3]
   SEPAR2[1]='Ä'
   SEPAR2[2]='Ä'
   SEPAR2[3]='Ä'

   SET CURSOR OFF
   CLEAR TYPEAHEAD
   SET COLOR TO COLOR6
   @24,1 SAY 'Buscar:                                                                       '
   SET COLOR TO COLOR7
   DBEDIT(9,1,18,78,CAMP2,'FUNMOD','',CABEZ2,SEPAR2)

   RESTORE SCREEN FROM JERI
   PASO=0
   IF LASTKEY()=13
      PASO=1
      STORE CODIGO TO VCODI_NV
      STORE DETALLE TO VDET_NV
      STORE CODIGBARRA TO VCODB_NV
      STORE CONIVA TO VPRE_NV
   ELSE
      USE STOCK INDEX ORDCOD
      GO TOP
      SEEK VCODI_OR
      STORE CANTIDAD TO VCANTI
   ENDIF

   @10,2 SAY 'C¢d.BarraÄÄÄÄ>: '
   @12,2 SAY 'C¢digoÄÄÄÄÄÄÄ>: '
   @14,2 SAY 'DetalleÄÄÄÄÄÄ>: '
   @16,2 SAY 'Precio UnitÄÄ>: '
   SET COLOR TO COLOR6

   IF PASO=1
      @10,18 SAY VCODB_NV
      @12,18 SAY VCODI_NV
      @14,18 SAY VDET_NV
      @16,18 SAY ALLTRIM(STR(VPRE_NV))
   ELSE
      @10,18 SAY VCODB_OR
      @12,18 SAY VCODI_OR
      @14,18 SAY VDET_OR
      @16,18 SAY ALLTRIM(STR(VPRE_OR))
   ENDIF

   SET COLOR TO COLOR0
   DO WHILE .T.
      SET CURSOR ON
      STORE VCANT_OR TO VCANT_NV
      @18,2 SAY 'CantidadÄÄÄÄÄ>:'GET VCANT_NV
      READ

      IF LASTKEY()=27
         RETURN
      ENDIF

      IF VCANT_NV>VCANTI
         SET CURSOR OFF
         SAVE SCREEN TO YAMA
         SET COLOR TO COLOR0
         @19,20 TO 21,59
         @20,22 SAY 'La cantidad es SUPERIOR al stock'
         SET COLOR TO COLOR9
         @20,37 SAY 'SUPERIOR'
         SET COLOR TO COLOR0
         TONE(1200,1)
         INKEY(3)
         RESTORE SCREEN FROM YAMA
         LOOP
      ENDIF
      EXIT
   ENDDO

   SET COLOR TO COLOR0
   @20,2 SAY 'OperadorÄÄÄÄÄ>: '
   SET COLOR TO COLOR6
   @20,18 SAY VOPER

   IF PASO=1
      STORE VCANT_NV*VPRE_NV TO VSUB_NV
   ELSE
      STORE VCANT_NV*VPRE_OR TO VSUB_NV
   ENDIF

   STORE VTOT_OR-VSUB_OR+VSUB_NV TO VTOT_NV
   SET CURSOR OFF
   SET COLOR TO COLOR0
   @24,26 SAY '¨ Modificaci¢n correcta (S/N) ?'
   SET COLOR TO COLOR3
   @24,51 SAY 'S'
   @24,53 SAY 'N'

   SET COLOR TO COLOR0
   DO WHILE .T.
      INKEY(0)
      IF LASTKEY()<>78.AND.LASTKEY()<>83.AND.LASTKEY()<>110.AND.LASTKEY()<>115
         TONE(500,1)
         LOOP
      ENDIF
      EXIT
   ENDDO

   IF LASTKEY()=83.OR.LASTKEY()=115
      USE STOCK INDEX ORDCOD
      GO TOP

      IF PASO=1
         SEEK VCODI_OR
         STORE CANTIDAD+VCANT_OR TO NCANT
         REPLACE CANTIDAD WITH NCANT

         GO TOP
         SEEK VCODI_NV
         STORE CANTIDAD-VCANT_NV TO NCANT
         REPLACE CANTIDAD WITH NCANT
      ELSE
         SEEK VCODI_OR
         STORE CANTIDAD+VCANT_OR-VCANT_NV TO NCANT
         REPLACE CANTIDAD WITH NCANT
      ENDIF

      USE VENTAS INDEX ORDFEC
      SET FILTER TO FECHA>=DESDE.AND.FECHA<=HASTA
      GO TOP
      GO REGISTRO

      IF PASO=1
         REPLACE CODIGO WITH VCODI_NV,CANTIDAD WITH VCANT_NV,DETALLE WITH VDET_NV
         REPLACE CODIGBARRA WITH VCODB_NV,PRECIO WITH VPRE_NV,SUBTOTAL WITH VSUB_NV
         REPLACE TOTAL WITH VTOT_NV
      ELSE
         REPLACE CANTIDAD WITH VCANT_NV,SUBTOTAL WITH VSUB_NV,TOTAL WITH VTOT_NV
      ENDIF

      SET FILTER TO

      USE BASECAJA
      INDEX ON NUMEROCAJA TO ORDCAJA
      SET FILTER TO NUMEROCAJA=NUMACT-1
      GO TOP

      STORE TOTVENTAS TO TVENTAS
      STORE ENCAJA TO TEXISTE
      STORE DEBERIA TO TDEBERIA
      STORE TVENTAS-VTOT_OR+VTOT_NV TO TVENTAS2
      STORE TDEBERIA-VTOT_OR+VTOT_NV TO TDEBERIA2
      REPLACE TOTVENTAS WITH TVENTAS2,DEBERIA WITH TDEBERIA2
   ENDIF
   SET CURSOR OFF
ENDIF

RESTORE SCREEN FROM TATITA

DO MODVTAS

IF LASTKEY()=27
   RETURN
ENDIF

RETURN

FUNCTION FUNVTA
PARAMETERS MODE
PUBLIC INTER

DO CASE
    CASE MODE=1
        TONE(500,2)
        RETURN(1)
    CASE MODE=2
        TONE(500,2)
        RETURN(1)
    CASE MODE=0
        RETURN(1)
    CASE LASTKEY()=13
        RETURN(0)
    CASE LASTKEY()=7
        DELETE
        PACK
        RETURN(2)
    CASE LASTKEY()=27
        RETURN(0)
    OTHERWISE

        IF LASTKEY()=8
           STORE '' TO KK
           SET COLOR TO COLOR6
           @24,1 SAY 'Buscar:                                                                       '
           @24,1 SAY ''
           SET COLOR TO COLOR0
           GO TOP
           RETURN(1)
        ENDIF

        SET CURSOR OFF
        SET COLOR TO COLOR6
        @24,1 SAY 'Buscar:                                                                       '
        @24,1 SAY ''
        STORE KK+UPPER(CHR(LASTKEY())) TO KK
        STORE LEN(KK) TO LL
        @24,9 SAY KK
        SET COLOR TO COLOR0
        GO TOP
        seek KK

        IF .NOT. FOUND()
            SET COLOR TO COLOR6
            @24,46 SAY 'Pulse <ÄÄÄ para volver a empezar'
            SET COLOR TO COLOR13
            @24,52 SAY '<ÄÄÄ'
            SET COLOR TO COLOR0
        ENDIF

        RETURN(1)
ENDCASE
RETURN NIL
