#include "colores.ch"
SAVE SCREEN TO AA
SET EXACT OFF
@12,12 TO 14,66
@13,13 CLEAR TO 13,65
IF !FILE('.\ESC\PASS.OVL')
   TONE(500,2)
   SET COLOR TO COLOR8
   @13,23 SAY 'El Archivo de Clave NO EXISTE'
   INKEY(4)
   RETURN
ENDIF
TONE(500,2)
SET CURSOR ON
STORE SPACE(12) TO ESCLAVE
SET COLOR TO COLOR10
@13,29 SAY 'Ingrese Clave: '
SET COLOR TO N/N,N/N
@13,43 SAY ''GET ESCLAVE PICTURE '@!'
READ
IF LASTKEY()=27
   RETURN
ENDIF
SET CURSOR OFF
XX=LEN(ALLTRIM(ESCLAVE))
SET COLOR TO COLOR0
STORE FOPEN('.\ESC\PASS.OVL',2) TO CARAC
FSEEK (CARAC,0,0)
STORE SPACE(12) TO VXT
STORE FREAD(CARAC,@VXT,12) TO NUM
FSEEK (CARAC,0,0)
STORE FREADSTR(CARAC,NUM) TO WORD
FCLOSE(CARAC)
CLAVE=''
FOR TT=1 TO XX
   STORE SUBSTR(ESCLAVE,TT,1) TO ZZ
   STORE ASC(ZZ)+XX+90 TO YY
   STORE CHR(YY) TO ESTA
   CLAVE=CLAVE+ESTA
NEXT
STORE CLAVE TO ESCLAVE
@13,13 CLEAR TO 13,65
IF WORD==CLAVE
   SET COLOR TO COLOR0
   TONE (1000,3)
   STORE 1 TO CORRECTO
ELSE
   SET COLOR TO COLOR8
   @13,32 SAY 'Clave INCORRECTA'
   SET COLOR TO COLOR0
   TONE (1000,3)
   INKEY(3)
   STORE 0 TO CORRECTO
ENDIF
SET COLOR TO COLOR0
RESTORE SCREEN FROM AA

RETURN
