REM  Compile The Source Files
NGC tool_001.txt
NGC tool_002.txt
NGC tool_003.txt
NGC tool_004.txt
NGC tool_005.txt
NGC tool_006.txt
NGC tool_007.txt
NGC tool_008.txt
NGC tool_009.txt
NGC tool_010.txt
NGC tool_011.txt
NGC tool_012.txt
NGC tool_013.txt
NGC tool_014.txt
NGC tool_015.txt
NGC tool_016.txt
NGC tool_017.txt

REM Link the Source Files to Create a Database. 
NGML tools1-3.lnk
