#include "colores.ch"

STORE SPACE(60) TO VDETALLE
STORE 0 TO VCODIGO
STORE 0 TO VBARRA
STORE 0 TO VDETALLE
STORE 0 TO VPCOSTO
STORE 0 TO VCONIVA
STORE 0 TO VSTOCK
STORE 0 TO VCANT
STORE 0 TO NUEVO
STORE 0 TO VLIMI
STORE 0 TO SALE
STORE 1 TO SIGUE

SAVE SCREEN TO BOLUDO
USE MERCA
INDEX ON CODIGO TO ORDCOD
INDEX ON DETALLE TO ORDDET
INDEX ON CODIGBARRA TO ORDBARRA
GO TOP

SAVE SCREEN TO CAM

***********************


    DO WHILE .T.
     GET_BARRA()

     IF SALE=1
        EXIT
     ENDIF

     IF SIGUE=1
       MOD_STK2()
     ENDIF

     RESTORE SCREEN FROM CAM

     IF SALE=1
        EXIT
     ENDIF


LOOP
ENDDO

****************************
IF SIGUE=0
  RETURN
ENDIF

STORE 0 TO SALE

IF VBARRA=0
    DO WHILE .T.
      IF SALE=1
        EXIT
      ENDIF

      EDITAR2()

      IF SALE=1
        EXIT
      ENDIF

      MOD_STK2()
    LOOP
    ENDDO
ENDIF


FUNCTION GET_BARRA
   STORE 0 TO VBARRA
   USE MERCA INDEX ORDBARRA
   GO TOP
   @18,13 CLEAR TO 20,65
   STORE 0 TO VBARRA
   set color to COLOR8
   @3,20 say ' INGRESO      '
   set color to COLOR0
   SAVE SCREEN TO JERI
   @18,19 TO 20,60
   @19,20 CLEAR TO 19,59
   SET COLOR TO GET01
   SET CURSOR ON
   @19,21 SAY 'C¢digo de barras:'GET VBARRA PICTURE '99999999999999'
   READ

   IF LASTKEY()=27
      STORE 1 TO SALE
      STORE 0 TO SIGUE
      RETURN NIL
   ENDIF

   IF VBARRA=0
      STORE 1 TO SALE
      RETURN NIL
   ENDIF

      SEEK VBARRA
      IF FOUND()=.T.
         STORE CODIGO TO VCODIGO
         STORE DETALLE TO VDETALLE
         STORE PCOSTO TO VPCOSTO
         STORE CONIVA TO VCONIVA
      ELSE
         @19,20 CLEAR TO 19,59
         set color to COLOR8
         @19,27 SAY 'C¢digo de barras INEXISTENTE'
         set color to COLOR0
         STORE 0 TO SIGUE
         INKEY(3)
         RETURN NIL
      ENDIF

      USE .\ESC\STOCK
      INDEX ON CODIGO TO ORDCODI
      GO TOP
      SEEK VCODIGO

      IF FOUND()=.T.
          STORE CANTIDAD TO VSTOCK
          STORE LIMITE TO VLIMI
      ENDIF

STORE 0 TO SALE
STORE 1 TO SIGUE
RETURN NIL





function EDITAR2
STORE 0 TO VCANT
STORE 0 TO VLIMI

USE MERCA INDEX ORDDET
GO TOP

*RESTORE SCREEN FROM JERI
SET COLOR TO COLOR4
@8,1 TO 23,78
@9,2 CLEAR TO 22,76
@21,2 TO 21,77
@19,2 TO 19,77
@20,2 CLEAR TO 20,77
@22,2 CLEAR TO 22,77
@22,5 SAY '        Tomar'
@22,45 SAY 'Por C¢digo -      Por Detalle'
@22,24 SAY '      Salir'
SET COLOR TO COLOR10
@20,28 SAY 'Fichero de Art¡culos'
@22,5 SAY '<ENTER>'
@22,24 SAY '<ESC>'
@22,40 SAY '<F2>'
@22,58 SAY '<F3>'

DECLARE CAMP[2]
CAMP[1]='CODIGO'
CAMP[2]='DETALLE'
DECLARE CABEZ[2]
CABEZ[1]=' C¢digo'
CABEZ[2]='                       Detalle'

DECLARE SEPAR[2]
SEPAR[1]='Ä'
SEPAR[2]='Ä'
CLEAR TYPEAHEAD

SET COLOR TO COLOR6
@24,1 SAY 'Buscar:                                                                       '
SET COLOR TO COLOR7
DBEDIT(9,2,18,77,CAMP,'FUNMOD','',CABEZ,SEPAR)

IF LASTKEY()=27
   STORE 1 TO SALE
   RETURN NIL
ENDIF

IF LASTKEY()=-1
   USE MERCA INDEX ORDCOD
   GO TOP
ENDIF

IF LASTKEY()=-2
   USE MERCA INDEX ORDDET
   GO TOP
ENDIF

STORE CODIGO TO VCODIGO
STORE DETALLE TO VDETALLE
STORE CODIGBARRA TO VBARRA
STORE PCOSTO TO VPCOSTO
STORE CONIVA TO VCONIVA

USE .\ESC\STOCK
INDEX ON CODIGO TO .\ESC\ORDCOD
GO TOP

SEEK VCODIGO
IF FOUND()=.T.
   STORE CANTIDAD TO Vstock
   STORE LIMITE TO VLIMI
   STORE REAL TO VREAL
ENDIF

RETURN NIL












FUNCTION MOD_STK2
   CLEAR
   @0,0 TO 2,30
   SET COLOR TO COLOR3
   @1,2 SAY 'ESTACION DE SERVICIO CENTRO'
   numero=LEFT(DTOC(DATE()),2)
   DIA=TDIAS(cdow(DATE()))
   MES=TMES(CMONTH(DATE()))
   ANIO=ALLTRIM(STR(YEAR(DATE())))
   VFECHA=DIA+' '+numero+' de '+MES+' de '+ANIO
   LL=79-LEN(VFECHA)
   SET COLOR TO COLOR0
   @1,LL-7 SAY 'Fecha: '
   SET COLOR TO COLOR3
   @1,LL SAY VFECHA

   SET CURSOR ON
   SET COLOR TO COLOR0
   @6,0 SAY REPLICATE('Ä',79)
   SET CONFIRM OFF

   SET COLOR TO COLOR0
   @8,0 SAY REPLICATE('Ä',79)
   @10,0 SAY REPLICATE('Ä',79)
   @12,0 SAY REPLICATE('Ä',79)
   @14,0 SAY REPLICATE('Ä',79)
   @16,0 SAY REPLICATE('Ä',79)
   @18,0 SAY REPLICATE('Ä',79)

   @7,1 SAY 'C¢digo :'
   @9,1 SAY 'Detalle:'
   @11,1 SAY 'C¢digo de Barra:'
   @13,1 SAY 'Precio de Costo:                            Precio de Venta:'
   @15,1 SAY 'Ingrese Nuevo Stock:'
   @17,1 SAY 'L¡mite de reposicion:'

   SET COLOR TO COLOR6
   @7,10 SAY VCODIGO
   @9,10 SAY VDETALLE
   @11,18 SAY VBARRA
   @13,18 SAY VPCOSTO
   @13,62 SAY VCONIVA
   SET COLOR TO COLOR9

   SET COLOR TO GET01
   @15,21 SAY ''GET VSTOCK PICTURE '9999'
   @17,23 SAY ''GET VLIMI PICTURE '99999'

   READ
   STORE VSTOCK+VCANT TO VCANT

   SET CURSOR OFF
   @23,25 SAY '¨ Grabar este ingreso (S/N) ?'
   SET COLOR TO COLOR3
   @23,48 SAY 'S'
   @23,50 SAY 'N'
   SET COLOR TO COLOR0

INKEY(0)
   IF LASTKEY()=78.OR.LASTKEY()=110
      RETURN NIL
   ENDIF

  IF LASTKEY()=83.OR.LASTKEY()=115
      USE .\ESC\STOCK
      INDEX ON CODIGO TO ORDSTK UNIQUE
      GO TOP
      SEEK VCODIGO

      IF FOUND()=.T.
         REPLACE CANTIDAD WITH VSTOCK
         REPLACE LIMITE WITH VLIMI
      ELSE
         APPEND BLANK
         REPLACE CODIGO WITH VCODIGO
         REPLACE CANTIDAD WITH VSTOCK
         REPLACE LIMITE WITH VLIMI
      ENDIF
  ENDIF
RETURN NIL
