DECLARE CAMP[12]
CAMP[1]='HORAAP'
CAMP[2]='HORACI'
CAMP[3]='FECHA'
CAMP[4]='OPERADOR'
CAMP[5]='VENTAS'
CAMP[6]='GASTOS'
CAMP[7]='TOTCAJA'
CAMP[8]='EFENCAJA'
CAMP[9]='NUMEROCAJA'
CAMP[10]='INICIAL'
CAMP[11]='DIFER'
CAMP[12]='CANTVTAS'


DECLARE TIPO[12]
TIPO[1]='C'
TIPO[2]='C'
TIPO[3]='D'
TIPO[4]='C'
TIPO[5]='N'
TIPO[6]='N'
TIPO[7]='N'
TIPO[8]='N'
TIPO[9]='N'
TIPO[10]='N'
TIPO[11]='N'
TIPO[12]='N'

DECLARE LON[12]
LON[1]=8
LON[2]=8
LON[3]=8
LON[4]=10
LON[5]=8
LON[6]=8
LON[7]=8
LON[8]=8
LON[9]=5
LON[10]=8
LON[11]=8
LON[12]=5

DECLARE DECI[12]
DECI[1]=0
DECI[2]=0
DECI[3]=0
DECI[4]=0
DECI[5]=2
DECI[6]=2
DECI[7]=2
DECI[8]=2
DECI[9]=0
DECI[10]=2
DECI[11]=2
DECI[12]=0


ERASE CAJAS.DBF
ERASE TEMP.DBF

CREATE TEMP
store 1 to I

do while .t.
   APPEND BLANK
   REPLACE field_name with CAMP[I]
   REPLACE field_type with tipo[I]
   REPLACE field_len with lon[I]
   REPLACE field_dec with deci[I]

   if i=12
     exit
   endif

   store i+1 to i
   loop
enddo

CREATE .\new\CAJAS FROM TEMP
ERASE TEMP.DBF
 

STORE SPACE(10) TO VHORACI

STORE 0 TO FECHA
STORE SPACE(10) TO OPERADOR
STORE 0 TO VENTAS
STORE 0 TO GASTOS
STORE 0 TO TOTCAJA
STORE 0 TO EFENCAJA
STORE 0 TO NUMEROCAJA
STORE 0 TO INICIAL
STORE 0 TO DIFER
STORE 0 TO CANTVTAS

STORE 1 TO IR
store 0 to sale

DO WHILE .T.
  USE BASECAJA
  GO IR
  IF EOF()
    store 1 to sale
  ENDIF
  ? IR
  STORE IR+1 TO IR

  STORE FECHA TO VFECHA
  STORE HORA TO VHORACI
  STORE OPERADOR TO VOPERADOR
  STORE TOTVENTAS TO VTOTVENTAS
  STORE TOTGASTOS TO VGASTOS
  STORE ENCAJA TO VENCAJA
  STORE DEBERIA TO VDEBERIA
  STORE NUMEROCAJA TO VNUMEROCAJA

  USE .\NEW\CAJAS
  APPEND BLANK

  REPLACE FECHA WITH VFECHA
  REPLACE HORACI WITH VHORACI
  REPLACE OPERADOR WITH VOPERADOR
  REPLACE VENTAS WITH VTOTVENTAS
  REPLACE GASTOS WITH VGASTOS
  REPLACE NUMEROCAJA WITH VNUMEROCAJA
  REPLACE INICIAL WITH VENCAJA
  REPLACE TOTCAJA WITH VDEBERIA
if sale=1
  exit
endif
LOOP
ENDDO

