
CREA_BASE()
DATOS_1()
CREA_MERCA()
CREA_STOCK()
SEPARA_DAT()


FUNCTION CREA_BASE
?
? "CREA BASE"
?
DECLARE CAMP[11]
CAMP[1]='MARCA'
CAMP[2]='CODIGO'
CAMP[3]='DETALLE'
CAMP[4]='CODIGBARRA'
CAMP[5]='PCOSTO'
CAMP[6]='CONIVA'
CAMP[7]='CANTIDAD'
CAMP[8]='REAL'
CAMP[9]='LIMITE'
CAMP[10]='GANANCIA'
CAMP[11]='SINIVA'

DECLARE TIPO[11]
TIPO[1]='C'
TIPO[2]='N'
TIPO[3]='C'
TIPO[4]='N'
TIPO[5]='N'
TIPO[6]='N'
TIPO[7]='N'
TIPO[8]='N'
TIPO[9]='N'
TIPO[10]='N'
TIPO[11]='N'

DECLARE LON[11]
LON[1]=1
LON[2]=6
LON[3]=60
LON[4]=14
LON[5]=8
LON[6]=8
LON[7]=5
LON[8]=5
LON[9]=5
LON[10]=3
LON[11]=8

DECLARE DECI[11]
DECI[1]=0
DECI[2]=0
DECI[3]=0
DECI[4]=0
DECI[5]=2
DECI[6]=2
DECI[7]=0
DECI[8]=0
DECI[9]=0
DECI[10]=0
DECI[11]=2


ERASE SWAP.DBF
ERASE TEMP.DBF

CREATE TEMP
store 1 to I

do while .t.
   APPEND BLANK
   REPLACE field_name with CAMP[I]
   REPLACE field_type with tipo[I]
   REPLACE field_len with lon[I]
   REPLACE field_dec with deci[I]

   if i=11
     exit
   endif

   store i+1 to i
   loop
enddo

CREATE SWAP FROM TEMP
ERASE TEMP.DBF
RETURN NIL



FUNCTION DATOS_1
?
? "DATOS SWAP"
?

STORE SPACE(60) TO DETALLE
STORE 0 TO VCODIGBARRA
STORE 0 TO VPCOSTO
STORE 0 TO VGANANCIA
STORE 0 TO VSINIVA
STORE 0 TO VCONIVA

STORE 0 TO VCANTIDAD
STORE 0 TO VREAL
STORE 0 TO VLIMITE

USE MERCA
INDEX ON CODIGO TO MERCA

USE STOCK
INDEX ON CODIGO TO STOCK

STORE 1 TO IR
STORE 0 TO SALE
DO WHILE .T.


  USE MERCA
  SET INDEX TO MERCA
  GO IR

  IF EOF()
    STORE 1 TO SALE
  ENDIF

  STORE CODIGO TO VCODIGO
  STORE DETALLE TO VDETALLE
  STORE CODIGBARRA TO VCODIGBARRA
  STORE PCOSTO TO VPCOSTO
  STORE GANANCIA TO VGANANCIA
  STORE SINIVA TO VSINIVA
  STORE CONIVA TO VCONIVA

  USE STOCK
  SET INDEX TO STOCK
  GO TOP

  SEEK VCODIGO
  IF FOUND()=.T.
     STORE CANTIDAD TO VCANTIDAD
     STORE REAL TO VREAL
     STORE LIMITE TO VLIMITE
  ELSE
     STORE 0 TO VCANTIDAD
     STORE 0 TO VREAL
     STORE 0 TO VLIMITE
  ENDIF

  USE SWAP
  APPEND BLANK

  STORE VAL(VCODIGBARRA) TO VCODIGBARRA

  REPLACE CODIGO WITH IR
  REPLACE DETALLE WITH VDETALLE
  REPLACE CODIGBARRA WITH VCODIGBARRA
  REPLACE PCOSTO WITH VPCOSTO
  REPLACE GANANCIA WITH VGANANCIA
  REPLACE SINIVA WITH VSINIVA
  REPLACE CONIVA WITH VCONIVA
  REPLACE CANTIDAD WITH VCANTIDAD
  REPLACE REAL WITH VREAL
  REPLACE LIMITE WITH VLIMITE

  ? IR
  STORE IR+1 TO IR
IF SALE=1
  EXIT
ENDIF
  LOOP
ENDDO
RETURN NIL


FUNCTION CREA_MERCA
?
? "CREA MERCA"
?

DECLARE CAMP[8]
CAMP[1]='MARCA'
CAMP[2]='CODIGO'
CAMP[3]='DETALLE'
CAMP[4]='CODIGBARRA'
CAMP[5]='PCOSTO'
CAMP[6]='GANANCIA'
CAMP[7]='SINIVA'
CAMP[8]='CONIVA'


DECLARE TIPO[8]
TIPO[1]='C'
TIPO[2]='N'
TIPO[3]='C'
TIPO[4]='N'
TIPO[5]='N'
TIPO[6]='N'
TIPO[7]='N'
TIPO[8]='N'

DECLARE LON[8]
LON[1]=1
LON[2]=6
LON[3]=60
LON[4]=14
LON[5]=8
LON[6]=3
LON[7]=8
LON[8]=8

DECLARE DECI[8]
DECI[1]=0
DECI[2]=0
DECI[3]=0
DECI[4]=0
DECI[5]=2
DECI[6]=0
DECI[7]=2
DECI[8]=2


ERASE MERNEW.DBF
ERASE TEMP.DBF

CREATE TEMP
store 1 to I

do while .t.
   APPEND BLANK
   REPLACE field_name with CAMP[I]
   REPLACE field_type with tipo[I]
   REPLACE field_len with lon[I]
   REPLACE field_dec with deci[I]

   if i=8
     exit
   endif

   store i+1 to i
   loop
enddo

CREATE .\NEW\MERCA FROM TEMP
ERASE .\NEW\TEMP.DBF
RETURN NIL




FUNCTION CREA_STOCK
?
? "CREA STOCK"
?

DECLARE CAMP[4]
CAMP[1]='CODIGO'
CAMP[2]='CANTIDAD'
CAMP[3]='REAL'
CAMP[4]='LIMITE'

DECLARE TIPO[8]
TIPO[1]='N'
TIPO[2]='N'
TIPO[3]='N'
TIPO[4]='N'

DECLARE LON[8]
LON[1]=6
LON[2]=6
LON[3]=6
LON[4]=6

DECLARE DECI[8]
DECI[1]=0
DECI[2]=0
DECI[3]=0
DECI[4]=0


ERASE STKNEW.DBF
ERASE TEMP.DBF

CREATE TEMP
store 1 to I

do while .t.
   APPEND BLANK
   REPLACE field_name with CAMP[I]
   REPLACE field_type with tipo[I]
   REPLACE field_len with lon[I]
   REPLACE field_dec with deci[I]

   if i=4
     exit
   endif

   store i+1 to i
   loop
enddo

CREATE .\NEW\STOCK FROM TEMP
ERASE TEMP.DBF
RETURN NIL






FUNCTION SEPARA_DAT
?
? "SEPARA DATOS"
?

USE SWAP
INDEX ON CODIGO TO SWAP

STORE 1 TO IR
STORE 0 TO SALE

DO WHILE .T.
  USE SWAP
  SET INDEX TO SWAP
  GO IR

  IF EOF()
    STORE 1 TO SALE
  ENDIF

  STORE CODIGO TO VCODIGO,VCODIGO2
  STORE DETALLE TO VDETALLE
  STORE CODIGBARRA TO VCODIGBARRA
  STORE PCOSTO TO VPCOSTO
  STORE GANANCIA TO VGANANCIA
  STORE SINIVA TO VSINIVA
  STORE CONIVA TO VCONIVA
  STORE CANTIDAD TO VCANTIDAD
  STORE REAL TO VREAL
  STORE LIMITE TO VLIMITE

  USE .\NEW\MERCA
  APPEND BLANK
  REPLACE CODIGO WITH VCODIGO
  REPLACE DETALLE WITH VDETALLE
  REPLACE CODIGBARRA WITH VCODIGBARRA
  REPLACE PCOSTO WITH VPCOSTO
  REPLACE GANANCIA WITH VGANANCIA
  REPLACE SINIVA WITH VSINIVA
  REPLACE CONIVA WITH VCONIVA

  USE .\NEW\STOCK
  APPEND BLANK
  REPLACE CODIGO WITH VCODIGO2
  REPLACE CANTIDAD WITH VCANTIDAD
  REPLACE REAL WITH VREAL
  REPLACE LIMITE WITH VLIMITE

  ? IR
  STORE IR+1 TO IR
IF SALE=1
   EXIT
ENDIF
  LOOP
ENDDO
RETURN NIL
