0001 001b 02d650  ERRORLEVEL  007a4a                                   C/ASM  CERO.EXE
0001 001c 02d650  __QUIT      007a78                                   C/ASM  CERO.EXE
0001 0019 02d650  PROCNAME    010816                                   C/ASM  CERO.EXE
0001 001a 02d650  PROCLINE    01084e                                   C/ASM  CERO.EXE
0001 000f 02d650  ERRORBLOCK  013ae8                                   C/ASM  CERO.EXE
0001 0014 02d650  NETERR      013b7c                                   C/ASM  CERO.EXE
0001 0017 02d650  ALERT       01c6f4                                   C/ASM  CERO.EXE
0001 0018 02d650  OUTERR      01cb4a                                   C/ASM  CERO.EXE
0001 002e 02d650  RDDREGISTE  01d5a0                                   C/ASM  CERO.EXE
0001 0025 02d650  RDDSETDEFA  01d840                                   C/ASM  CERO.EXE
0001 0002 02d650  DBUSEAREA   01d982                                   C/ASM  CERO.EXE
0001 0003 02d650  DBEVAL      01de7a                                   C/ASM  CERO.EXE
0001 0006 02d650  __DBZAP     01e252                                   C/ASM  CERO.EXE
0001 002c 02d650  _VDBFNTX    032e88                                   C/ASM  CERO.EXE
0001 0030 02d650  _VDBF       033482                                   C/ASM  CERO.EXE
0001 0001 02d650  CERO        034c00   DYN                                    CERO.EXE
0001 000b 02d650  CLIPINIT$   034ea6   DYN   INIT PROC                        CERO.EXE
0001 000e 02d650  SYSINIT     034ebc   DYN                                    CERO.EXE
0001 000d 02d650  ERRORSYS    034ec0   DYN                                    CERO.EXE
0001 0015 02d650  ERRORMESSA  034eda   DYN   STATIC                           CERO.EXE
0001 0023 02d650  RDDINIT$    034fec   DYN   INIT PROC                        CERO.EXE
0001 0010 02d650  DEFERROR    035000   DYN   STATIC                           CERO.EXE
0001 0026 02d650  RDDSYS      035243   DYN                                    CERO.EXE
0001 0027 02d650  INITHANDL$  035247   DYN   INIT PROC                        CERO.EXE
0001 0028 02d650  LOCKERRHAN  03526b   DYN   STATIC                           CERO.EXE
0001 002a 02d650  _NTXERR     035294   DYN                                    CERO.EXE
0001 002b 02d650  DBFNTXINI$  035298   DYN   INIT PROC                        CERO.EXE
0001 0024 02d650  DBFNTX      0352ac   DYN                                    CERO.EXE
0001 002f 02d650  DBFINIT$    0352b0   DYN   INIT PROC                        CERO.EXE
0001 002d 02d650  DBFONLY     0352c1   DYN                                    CERO.EXE
