REM  Compile The Source Files
NGC ck20_001.txt
NGC ck20_002.txt
NGC ck20_003.txt
NGC ck20_004.txt
NGC ck20_005.txt
NGC ck20_006.txt
NGC ck20_007.txt
NGC ck20_008.txt
NGC ck20_009.txt
NGC ck20_010.txt
NGC ck20_011.txt
NGC ck20_012.txt
NGC ck20_013.txt
NGC ck20_014.txt
NGC ck20_015.txt
NGC ck20_016.txt
NGC ck20_017.txt
NGC ck20_018.txt
NGC ck20_019.txt
NGC ck20_020.txt
NGC ck20_021.txt
NGC ck20_022.txt

REM Link the Source Files to Create a Database. 
NGML ck20.lnk
