REM  Compile The Source Files
NGC c52g_001.txt
NGC c52g_002.txt
NGC c52g_003.txt
NGC c52g_004.txt
NGC c52g_005.txt
NGC c52g_006.txt
NGC c52g_007.txt
NGC c52g_008.txt
NGC c52g_009.txt
NGC c52g_010.txt
NGC c52g_011.txt
NGC c52g_012.txt
NGC c52g_013.txt
NGC c52g_014.txt
NGC c52g_015.txt
NGC c52g_016.txt
NGC c52g_017.txt
NGC c52g_018.txt
NGC c52g_019.txt
NGC c52g_020.txt
NGC c52g_021.txt
NGC c52g_022.txt
NGC c52g_023.txt

REM Link the Source Files to Create a Database. 
NGML c52g01b.lnk
