0001 0011 01a310  ERRORLEVEL  006536                                   C/ASM  CUBO.EXE
0001 0012 01a310  __QUIT      006564                                   C/ASM  CUBO.EXE
0001 000f 01a310  PROCNAME    00ee6e                                   C/ASM  CUBO.EXE
0001 0010 01a310  PROCLINE    00eea6                                   C/ASM  CUBO.EXE
0001 0005 01a310  ERRORBLOCK  012140                                   C/ASM  CUBO.EXE
0001 000a 01a310  NETERR      0121d4                                   C/ASM  CUBO.EXE
0001 000d 01a310  ALERT       018608                                   C/ASM  CUBO.EXE
0001 000e 01a310  OUTERR      018a5e                                   C/ASM  CUBO.EXE
0001 0001 01a310  CUBO        01e400   DYN                                    CUBO.EXE
0001 0002 01a310  __APPINIT   01e404   DYN                                    CUBO.EXE
0001 0004 01a310  ERRORSYS    01e41d   DYN                                    CUBO.EXE
0001 0006 01a310  DEFERROR    01e443   DYN   STATIC                           CUBO.EXE
0001 0019 01a310  CLIPINIT$   01e6fb   DYN   INIT PROC                        CUBO.EXE
0001 001a 01a310  SYSINIT     01e711   DYN                                    CUBO.EXE
0001 000b 01a310  ERRORMESSA  01e800   DYN   STATIC                           CUBO.EXE
