0001 0018 02cf50  ERRORLEVEL  007a4a                                   C/ASM  INDC.EXE
0001 0019 02cf50  __QUIT      007a78                                   C/ASM  INDC.EXE
0001 0016 02cf50  PROCNAME    010816                                   C/ASM  INDC.EXE
0001 0017 02cf50  PROCLINE    01084e                                   C/ASM  INDC.EXE
0001 0002 02cf50  SET         010a0e                                   C/ASM  INDC.EXE
0001 000c 02cf50  ERRORBLOCK  013ae8                                   C/ASM  INDC.EXE
0001 0011 02cf50  NETERR      013b7c                                   C/ASM  INDC.EXE
0001 0014 02cf50  ALERT       01c6f4                                   C/ASM  INDC.EXE
0001 0015 02cf50  OUTERR      01cb4a                                   C/ASM  INDC.EXE
0001 0024 02cf50  ORDLISTADD  01cd96                                   C/ASM  INDC.EXE
0001 0026 02cf50  ORDLISTCLE  01ce4a                                   C/ASM  INDC.EXE
0001 0028 02cf50  ORDLISTREB  01ce74                                   C/ASM  INDC.EXE
0001 002a 02cf50  ORDSETFOCU  01ce9e                                   C/ASM  INDC.EXE
0001 002e 02cf50  ORDBAGEXT   01cf30                                   C/ASM  INDC.EXE
0001 002c 02cf50  ORDNUMBER   01d0b0                                   C/ASM  INDC.EXE
0001 0030 02cf50  ORDKEY      01d0bc                                   C/ASM  INDC.EXE
0001 0021 02cf50  ORDCONDSET  01d0d4                                   C/ASM  INDC.EXE
0001 0022 02cf50  ORDCREATE   01d166                                   C/ASM  INDC.EXE
0001 003c 02cf50  RDDREGISTE  01dafc                                   C/ASM  INDC.EXE
0001 0033 02cf50  RDDSETDEFA  01dd9c                                   C/ASM  INDC.EXE
0001 0003 02cf50  DBUSEAREA   01dede                                   C/ASM  INDC.EXE
0001 003a 02cf50  _VDBFNTX    032918                                   C/ASM  INDC.EXE
0001 003e 02cf50  _VDBF       032f12                                   C/ASM  INDC.EXE
0001 0001 02cf50  INDC        034400   DYN                                    INDC.EXE
0001 0008 02cf50  CLIPINIT$   03450c   DYN   INIT PROC                        INDC.EXE
0001 000b 02cf50  SYSINIT     034522   DYN                                    INDC.EXE
0001 000a 02cf50  ERRORSYS    034526   DYN                                    INDC.EXE
0001 000d 02cf50  DEFERROR    034540   DYN   STATIC                           INDC.EXE
0001 0020 02cf50  _DTXCONDSE  034783   DYN                                    INDC.EXE
0001 0004 02cf50  DBCREATEIN  0347af   DYN                                    INDC.EXE
0001 0023 02cf50  DBSETINDEX  0347cd   DYN                                    INDC.EXE
0001 0025 02cf50  DBCLEARIND  0347df   DYN                                    INDC.EXE
0001 0027 02cf50  DBREINDEX   0347ea   DYN                                    INDC.EXE
0001 002d 02cf50  INDEXEXT    0347f5   DYN                                    INDC.EXE
0001 0012 02cf50  ERRORMESSA  034800   DYN   STATIC                           INDC.EXE
0001 0029 02cf50  DBSETORDER  034912   DYN                                    INDC.EXE
0001 002b 02cf50  INDEXORD    034940   DYN                                    INDC.EXE
0001 002f 02cf50  INDEXKEY    034951   DYN                                    INDC.EXE
0001 0031 02cf50  RDDINIT$    034962   DYN   INIT PROC                        INDC.EXE
0001 0034 02cf50  RDDSYS      034975   DYN                                    INDC.EXE
0001 0035 02cf50  INITHANDL$  034979   DYN   INIT PROC                        INDC.EXE
0001 0036 02cf50  LOCKERRHAN  03499d   DYN   STATIC                           INDC.EXE
0001 0038 02cf50  _NTXERR     0349c6   DYN                                    INDC.EXE
0001 0039 02cf50  DBFNTXINI$  0349ca   DYN   INIT PROC                        INDC.EXE
0001 0032 02cf50  DBFNTX      0349de   DYN                                    INDC.EXE
0001 003d 02cf50  DBFINIT$    0349e2   DYN   INIT PROC                        INDC.EXE
0001 003b 02cf50  DBFONLY     0349f3   DYN                                    INDC.EXE
