DO WHILE .T.
   SET COLOR TO BG/B
   @4,17 TO 9,28
   @5,18 CLEAR TO 8,27
   SET COLOR TO BG+/B
   @5,19 SAY 'Modificar'
   SET COLOR TO BG/B,W+/B
   @7,18 PROMPT ' ARTICULO '
   @8,18 PROMPT ' FIRMAS   '
   PUBLIC OPC2
   MENU TO OPC2
   SET COLOR TO BG/B,W+/B
   DO CASE
      CASE OPC2=1
         DO MODMERC
      CASE OPC2=2
         DO MODFIRM
      OTHERWISE
         EXIT
   ENDCASE
   RESTORE SCREEN FROM ROMI
   LOOP
ENDDO
