SAVE SCREEN TO ROMI
DO WHILE .T.
   STORE SPACE(15) TO DESDE,HASTA
   SET CURSOR ON
   SET COLOR TO W+/B
   @16,6 TO 20,72 DOUBLE
   @17,7 CLEAR TO 19,71
   @17,7 SAY 'Desde Art¡culo:                   Hasta Art¡culo:'
   @19,26 SAY 'Pulse <ENTER> para tomar todos'
   SET COLOR TO B/W
   SET COLOR TO *BG+/B
   @19,33 SAY 'ENTER'
   SET COLOR TO BG/B,B/W
   @17,22 SAY ''GET DESDE PICTURE '@!'
   READ
   SET CURSOR OFF
   IF LASTKEY()=27
      RETURN
   ENDIF
   IF DESDE=SPACE(15)
      @17,7 CLEAR TO 19,71
      SET COLOR TO *RG+/B
      @17,35 SAY 'Tomando TODO'
      SET COLOR TO W+/B
      STORE '0' TO DESDE
      STORE 'ZZZZZZZZZZZZZZZ' TO HASTA
   ELSE
      SET CURSOR ON
      @19,7 CLEAR TO 19,71
      SET COLOR TO *RG+/B
      @19,33 SAY 'Tomando FRACCION'
      SET COLOR TO BG/B,B/W
      @17,56 SAY ''GET HASTA PICTURE '@!'
      READ
      IF LASTKEY()=27
         RETURN
      ENDIF
   ENDIF
   SET CURSOR OFF
   LD=LEN(ALLTRIM(DESDE))
   LH=LEN(ALLTRIM(HASTA))
   USE MERCA
   INDEX ON DETALLE TO ORDDET
   GO TOP
   COPY TO TEMPO FOR LEFT(DETALLE,LD)>=ALLTRIM(DESDE).AND.LEFT(DETALLE,LH)<=ALLTRIM(HASTA)
   USE TEMPO
   INDEX ON DETALLE TO ORDDET
   GO TOP
   IF EOF()
      TONE(500,2)
      SET COLOR TO W+/B
      @18,29 TO 20,48
      @19,30 CLEAR TO 19,47
      SET COLOR TO *R+/B
      @19,31 SAY 'NO EXISTEN DATOS'
      SET COLOR TO W+/B
      INKEY(3)
      RESTORE SCREEN FROM ROMI
      LOOP
   ENDIF
   DO LISTPREC
   RESTORE SCREEN FROM ROMI
   LOOP
ENDDO
