DECLARE CAMP[8]
CAMP[1]='CODIGO'
CAMP[2]='DETALLE'
CAMP[3]='CODIGBARRA'
CAMP[4]='PCOSTO'
CAMP[5]='CONIVA'
CAMP[6]='CANTIDAD'
CAMP[7]='REAL'
CAMP[8]='LIMITE'


DECLARE TIPO[8]
TIPO[1]='N'
TIPO[2]='C'
TIPO[3]='N'
TIPO[4]='N'
TIPO[5]='N'
TIPO[6]='N'
TIPO[7]='N'
TIPO[8]='N'

DECLARE LON[8]
LON[1]=6
LON[2]=60
LON[3]=14
LON[4]=8
LON[5]=8
LON[6]=6
LON[7]=6
LON[8]=6

DECLARE DECI[8]
DECI[1]=0
DECI[2]=0
DECI[3]=0
DECI[4]=2
DECI[5]=2
DECI[6]=0
DECI[7]=0
DECI[8]=0


ERASE STKNEW.DBF
ERASE TEMP.DBF

CREATE TEMP
store 1 to I

do while .t.
   APPEND BLANK
   REPLACE field_name with CAMP[I]
   REPLACE field_type with tipo[I]
   REPLACE field_len with lon[I]
   REPLACE field_dec with deci[I]

   if i=8
     exit
   endif

   store i+1 to i
   loop
enddo

CREATE STKNEW FROM TEMP
ERASE TEMP.DBF
 


STORE SPACE(30) TO DETALLE
STORE 0 TO VCODIGBARRA
STORE 0 TO VPCOSTO
STORE 0 TO VCONIVA
STORE 0 TO VCANTIDAD
STORE 0 TO VREAL
STORE 0 TO VLIMITE




STORE 1 TO IR

DO WHILE .T.
  USE STOCK
  GO IR
  IF EOF()
    EXIT
  ENDIF
  STORE IR+1 TO IR


STORE DETALLE TO VDETALLE
STORE CODIGBARRA TO VCODIGBARRA
STORE PCOSTO TO VPCOSTO
STORE CONIVA TO VCONIVA
STORE CANTIDAD TO VCANTIDAD
STORE REAL TO VREAL
STORE LIMITE TO VLIMITE
STORE VAL(VCODIGBARRA) TO VCODIGBARRA


USE STKNEW
APPEND BLANK

REPLACE CODIGO WITH IR
REPLACE DETALLE WITH VDETALLE
REPLACE CODIGBARRA WITH VCODIGBARRA
REPLACE PCOSTO WITH VPCOSTO
REPLACE CONIVA WITH VCONIVA
REPLACE CANTIDAD WITH VCANTIDAD
REPLACE REAL WITH VREAL
REPLACE LIMITE WITH VLIMITE


LOOP
ENDDO

