0001 0002 019ea0  SETFONT     00441b                                   C/ASM  STAN.EXE
0001 0012 019ea0  ERRORLEVEL  00653a                                   C/ASM  STAN.EXE
0001 0013 019ea0  __QUIT      006568                                   C/ASM  STAN.EXE
0001 0010 019ea0  PROCNAME    00b9b4                                   C/ASM  STAN.EXE
0001 0011 019ea0  PROCLINE    00b9ec                                   C/ASM  STAN.EXE
0001 0006 019ea0  ERRORBLOCK  00eb60                                   C/ASM  STAN.EXE
0001 000b 019ea0  NETERR      00ec06                                   C/ASM  STAN.EXE
0001 000e 019ea0  ALERT       015360                                   C/ASM  STAN.EXE
0001 000f 019ea0  OUTERR      0157b6                                   C/ASM  STAN.EXE
0001 0001 019ea0  STAN        01dc00   DYN                                    STAN.EXE
0001 0003 019ea0  __APPINIT   01dc1c   DYN                                    STAN.EXE
0001 0005 019ea0  ERRORSYS    01dc2c   DYN                                    STAN.EXE
0001 0007 019ea0  DEFERROR    01dc46   DYN   STATIC                           STAN.EXE
0001 000c 019ea0  ERRORMESSA  01de89   DYN   STATIC                           STAN.EXE
